// Auto-generated by build.rs - DO NOT EDIT
#![allow(non_snake_case, unused_braces)]
use dioxus::prelude::*;

#[component]
pub fn Home1(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M5.77778 10.2222V18C5.77778 19.1046 6.67321 20 7.77778 20H12M5.77778 10.2222L11.2929 4.70711C11.6834 4.31658 12.3166 4.31658 12.7071 4.70711L17.5 9.5M5.77778 10.2222L4 12M18.2222 10.2222V18C18.2222 19.1046 17.3268 20 16.2222 20H12M18.2222 10.2222L20 12M18.2222 10.2222L17.5 9.5M17.5 9.5V6M12 20V15",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Home2(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M5.77777 11.0507C5.77777 10.5202 5.98848 10.0115 6.36356 9.63644L11.2929 4.70711C11.6834 4.31658 12.3166 4.31658 12.7071 4.70711L17.6364 9.63644C18.0115 10.0115 18.2222 10.5202 18.2222 11.0506V18C18.2222 19.1046 17.3268 20 16.2222 20H12H7.77777C6.6732 20 5.77777 19.1046 5.77777 18V11.0507Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Palace(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            g { "clip-path": "url(#clip0_474_2)",
                path {
                    "d": "M24 0H0V24H24V0Z",
                    "fill": "white",
                    "fill-opacity": "0.01",
                }
                path {
                    "d": "M4 8.8H20L12 4L4 8.8Z",
                    "stroke": "black",
                    "stroke-width": "2",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
                path {
                    "d": "M20 19.4H4",
                    "stroke": "black",
                    "stroke-width": "2",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
                path {
                    "d": "M6 9V19",
                    "stroke": "black",
                    "stroke-width": "2",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
                path {
                    "d": "M10 9V19",
                    "stroke": "black",
                    "stroke-width": "2",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
                path {
                    "d": "M14 9V19",
                    "stroke": "black",
                    "stroke-width": "2",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
                path {
                    "d": "M18 9V19",
                    "stroke": "black",
                    "stroke-width": "2",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
            }
            defs {
                clipPath { "id": "clip0_474_2",
                    rect { "width": "24", "height": "24", "fill": "white" }
                }
            }
        
        }
    }
}

