[application]
tailwind_input = "tailwind.css"

[web.app]

# HTML title tag content
title = "Ratel"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[bundle]
identifier = "co.biyard.ratel"
publisher = "Biyard Corp."
icon = ["assets/icons/icon.icns","assets/favicon.ico"]
copyright = "Copyright 2023 Biyard Corp."
category = "Lifestyle"
short_description = ""
long_description = ""

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[android]
min_sdk = 24
target_sdk = 34