// Auto-generated by build.rs - DO NOT EDIT
#![allow(non_snake_case, unused_braces)]
use dioxus::prelude::*;

#[component]
pub fn Badge2(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width: width,
            height: height,
            view_box: "0 0 18 18",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
        path {
            "d": "M7.45141 2.48701C8.16541 1.34034 9.83459 1.34034 10.5486 2.48701C10.9613 3.14975 11.7499 3.47643 12.5104 3.2996C13.8261 2.99366 15.0063 4.17395 14.7004 5.48964C14.5236 6.25007 14.8502 7.03874 15.513 7.45141C16.6597 8.16541 16.6597 9.83459 15.513 10.5486C14.8502 10.9613 14.5236 11.7499 14.7004 12.5104C15.0063 13.8261 13.8261 15.0063 12.5104 14.7004C11.7499 14.5236 10.9613 14.8502 10.5486 15.513C9.83459 16.6597 8.16541 16.6597 7.45141 15.513C7.03874 14.8502 6.25007 14.5236 5.48964 14.7004C4.17395 15.0063 2.99366 13.8261 3.2996 12.5104C3.47643 11.7499 3.14975 10.9613 2.48701 10.5486C1.34034 9.83459 1.34034 8.16541 2.48701 7.45141C3.14975 7.03874 3.47643 6.25007 3.2996 5.48964C2.99366 4.17395 4.17395 2.99366 5.48964 3.2996C6.25007 3.47643 7.03874 3.14975 7.45141 2.48701Z",
            "fill": "#FCB300",
        }
        path {
            "d": "M6.51624 9.06108L8.13155 10.6764L11.4843 7.32361",
            "stroke": "#171717",
            "stroke-width": "1.5",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }

        }
    }
}

#[component]
pub fn Ellipse(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width: width,
            height: height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
        circle {
            "cx": "12",
            "cy": "12",
            "r": "8",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }

        }
    }
}

#[component]
pub fn Hexagon(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width: width,
            height: height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
        path {
            "d": "M11.5 4.28868C11.8094 4.11004 12.1906 4.11004 12.5 4.28868L18.4282 7.71132C18.7376 7.88996 18.9282 8.22008 18.9282 8.57735V15.4226C18.9282 15.7799 18.7376 16.11 18.4282 16.2887L12.5 19.7113C12.1906 19.89 11.8094 19.89 11.5 19.7113L5.5718 16.2887C5.2624 16.11 5.0718 15.7799 5.0718 15.4226V8.57735C5.0718 8.22008 5.2624 7.88996 5.5718 7.71132L11.5 4.28868Z",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }

        }
    }
}

#[component]
pub fn Pentagon(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width: width,
            height: height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
        path {
            "d": "M11.4122 4.42705C11.7627 4.17241 12.2373 4.17241 12.5878 4.42705L19.9717 9.7918C20.3222 10.0464 20.4689 10.4978 20.335 10.9098L17.5146 19.5902C17.3807 20.0022 16.9968 20.2812 16.5635 20.2812H7.43647C7.00325 20.2812 6.61929 20.0022 6.48542 19.5902L3.66501 10.9098C3.53113 10.4978 3.67779 10.0464 4.02828 9.7918L11.4122 4.42705Z",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }

        }
    }
}

#[component]
pub fn Pentagon2(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width: width,
            height: height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
        path {
            "d": "M24 0H0V24H24V0Z",
            "fill": "white",
            "fill-opacity": "0.01",
        }
        path {
            "d": "M12.3809 4L20.714 10.0543L17.7143 20H7.04766L4.04785 10.0543L12.3809 4Z",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linejoin": "round",
        }
        path {
            "d": "M17.7143 20L15.0476 16.9524",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }
        path {
            "d": "M7.04767 20L9.71433 16.9524",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }
        path {
            "d": "M4 10.0952L7.80952 11.2381",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }
        path {
            "d": "M20.762 10.0952L16.9525 11.2381",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }
        path {
            "d": "M12.381 4V7.80952",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }
        path {
            "d": "M12.381 7.80951L14.6695 9.55069L16.9524 11.2381L15.0477 16.9524H9.71433L7.80957 11.2381L10.0925 9.55069L12.381 7.80951Z",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linejoin": "round",
        }
        path {
            "d": "M6.13111 8.54071L4.04785 10.0543L4.79781 12.5407",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linejoin": "round",
        }
        path {
            "d": "M6.29767 17.5135L7.04762 20H9.71429",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linejoin": "round",
        }
        path {
            "d": "M15.0476 20H17.7143L18.4642 17.5135",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linejoin": "round",
        }
        path {
            "d": "M18.6306 8.54071L20.7138 10.0543L19.9639 12.5407",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linejoin": "round",
        }
        path {
            "d": "M14.4642 5.51358L12.3809 4L10.2977 5.51358",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linejoin": "round",
        }

        }
    }
}

#[component]
pub fn Square(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width: width,
            height: height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
        rect {
            "x": "4",
            "y": "4",
            "width": "16",
            "height": "16",
            "rx": "2",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }

        }
    }
}

#[component]
pub fn Star(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width: width,
            height: height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
        path {
            "d": "M11.0489 4.92705C11.3483 4.00574 12.6517 4.00574 12.9511 4.92705L14.2451 8.90983C14.379 9.32185 14.763 9.60081 15.1962 9.60081H19.3839C20.3527 9.60081 20.7554 10.8404 19.9717 11.4098L16.5838 13.8713C16.2333 14.126 16.0866 14.5773 16.2205 14.9894L17.5146 18.9721C17.8139 19.8934 16.7595 20.6596 15.9757 20.0902L12.5878 17.6287C12.2373 17.374 11.7627 17.374 11.4122 17.6287L8.02426 20.0902C7.24054 20.6596 6.18607 19.8934 6.48542 18.9721L7.7795 14.9894C7.91338 14.5773 7.76672 14.126 7.41623 13.8713L4.02827 11.4098C3.24456 10.8404 3.64734 9.60081 4.61606 9.60081H8.8038C9.23703 9.60081 9.62099 9.32185 9.75486 8.90983L11.0489 4.92705Z",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }

        }
    }
}

#[component]
pub fn Triangle(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width: width,
            height: height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
        path {
            "d": "M3.83827 18.5097L11.1284 5.54947C11.5107 4.86982 12.4893 4.86982 12.8716 5.54947L20.1617 18.5097C20.5367 19.1763 20.055 20 19.2902 20H4.70985C3.94502 20 3.46331 19.1763 3.83827 18.5097Z",
            "stroke": "black",
            "stroke-width": "2",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }

        }
    }
}

