// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

Future<IdentityResponse> createRandomIdentity({required String randomStr}) =>
    RustLib.instance.api.crateApiIcpIdentityCreateRandomIdentity(
      randomStr: randomStr,
    );

Future<IdentityResponse> createIdentity({required String privateKey}) => RustLib
    .instance
    .api
    .crateApiIcpIdentityCreateIdentity(privateKey: privateKey);

class IdentityResponse {
  final String address;
  final String publicKey;
  final String seed;
  final String privateKey;

  const IdentityResponse({
    required this.address,
    required this.publicKey,
    required this.seed,
    required this.privateKey,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      publicKey.hashCode ^
      seed.hashCode ^
      privateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityResponse &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          publicKey == other.publicKey &&
          seed == other.seed &&
          privateKey == other.privateKey;
}
