export { default as Ambulance } from './ambulance.svg';
export { default as Corona } from './corona.svg';
export { default as HeartRate1 } from './heart-rate-1.svg';
export { default as HeartRate } from './heart-rate.svg';
export { default as Mask } from './mask.svg';
export { default as Medicine } from './medicine.svg';
export { default as Sanitizer } from './sanitizer.svg';
export { default as Stethoscope } from './stethoscope.svg';
export { default as Syringe } from './syringe.svg';
