// Auto-generated by build.rs - DO NOT EDIT
#![allow(non_snake_case, unused_braces)]
use dioxus::prelude::*;

#[component]
pub fn Alarm(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            circle {
                "cx": "12",
                "cy": "13",
                "r": "8",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M12 9V13L15 15",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M18 3L21 6",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M6 3L3 6",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Clock(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            circle {
                "cx": "12",
                "cy": "12",
                "r": "9",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M12 6.5V12L16 14",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn History(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M5.52786 16.7023C6.6602 18.2608 8.3169 19.3584 10.1936 19.7934C12.0703 20.2284 14.0409 19.9716 15.7434 19.0701C17.446 18.1687 18.766 16.6832 19.4611 14.8865C20.1562 13.0898 20.1796 11.1027 19.527 9.29011C18.8745 7.47756 17.5898 5.96135 15.909 5.02005C14.2282 4.07875 12.2641 3.77558 10.3777 4.16623C8.49129 4.55689 6.80919 5.61514 5.64045 7.14656C4.47171 8.67797 3.89482 10.5797 4.01579 12.5023M4.01579 12.5023L2.51579 11.0023M4.01579 12.5023L5.51579 11.0023",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M12 8V12L15 15",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn HourglassOff(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M4 4L21 21",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M8 6.91406V7C8 9.20914 9.79086 11 12 11C12.0278 11 12.0554 10.9976 12.083 10.9971L17.9971 16.9111C17.9975 16.9407 18 16.9703 18 17V20C18.5523 20 19 20.4477 19 21C19 21.5523 18.5523 22 18 22H6C5.44772 22 5 21.5523 5 21C5 20.4477 5.44772 20 6 20V17C6 14.9129 7.06576 13.0749 8.68262 12C7.06576 10.9251 6 9.08709 6 7V4.91406L8 6.91406ZM12 13C9.79086 13 8 14.7909 8 17V20H16V17L15.9951 16.7939C15.8879 14.6806 14.14 13 12 13ZM18 2C18.5523 2 19 2.44772 19 3C19 3.55228 18.5523 4 18 4V7C18 8.93379 17.0836 10.6518 15.6631 11.749L14.2324 10.3184C15.2984 9.59983 16 8.38221 16 7V4H8V4.08594L5.91797 2.00391C5.94504 2.00171 5.97236 2 6 2H18Z",
                "fill": "black",
            }
        
        }
    }
}

#[component]
pub fn Hourglass(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M7 3H17V7C17 9.76142 14.7614 12 12 12V12C9.23858 12 7 9.76142 7 7V3Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M17 21L7 21L7 17C7 14.2386 9.23858 12 12 12V12C14.7614 12 17 14.2386 17 17L17 21Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M6 21H18",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M6 3H18",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn TimerOff(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M4 4L21 21",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "fill-rule": "evenodd",
                "clip-rule": "evenodd",
                "d": "M7.19155 6.60577C5.25324 8.06568 4 10.3865 4 13C4 17.4183 7.58172 21 12 21C14.6135 21 16.9343 19.7468 18.3942 17.8084L16.9612 16.3754C15.8812 17.9598 14.0621 19 12 19C8.68629 19 6 16.3137 6 13C6 10.9379 7.04024 9.11881 8.62458 8.03879L7.19155 6.60577ZM17.8316 14.4174C17.9417 13.9629 18 13.4883 18 13C18 9.68629 15.3137 7 12 7C11.5117 7 11.0371 7.05833 10.5826 7.16839L8.99696 5.58275C9.92422 5.20696 10.9379 5 12 5C13.5913 5 15.0741 5.46463 16.3202 6.26562L17.2929 5.29289C17.6834 4.90237 18.3166 4.90237 18.7071 5.29289C19.0976 5.68342 19.0976 6.31658 18.7071 6.70711L17.8602 7.55402C19.1879 8.98211 20 10.8962 20 13C20 14.0621 19.793 15.0758 19.4173 16.003L17.8316 14.4174ZM10 2C9.44772 2 9 2.44772 9 3C9 3.55228 9.44772 4 10 4H14C14.5523 4 15 3.55228 15 3C15 2.44772 14.5523 2 14 2H10Z",
                "fill": "black",
            }
        
        }
    }
}

#[component]
pub fn Timer(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M17 7L18 6",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M10 3H14",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            circle {
                "cx": "12",
                "cy": "13",
                "r": "7",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M12 13V10",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Update(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M18.4721 16.7023C17.3398 18.2608 15.6831 19.3584 13.8064 19.7934C11.9297 20.2284 9.95909 19.9716 8.25656 19.0701C6.55404 18.1687 5.23397 16.6832 4.53889 14.8865C3.84381 13.0898 3.82039 11.1027 4.47295 9.29011C5.12551 7.47756 6.41021 5.96135 8.09103 5.02005C9.77184 4.07875 11.7359 3.77558 13.6223 4.16623C15.5087 4.55689 17.1908 5.61514 18.3596 7.14656C19.5283 8.67797 20.1052 10.5797 19.9842 12.5023M19.9842 12.5023L21.4842 11.0023M19.9842 12.5023L18.4842 11.0023",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M12 8V12L15 15",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Watch(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M12 9.5V12L13.5 13.5",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            circle {
                "cx": "12",
                "cy": "12",
                "r": "6",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M8.5 17L8.78101 19.2481C8.90612 20.2489 9.75692 21 10.7656 21H13.2344C14.2431 21 15.0939 20.2489 15.219 19.2481L15.5 17",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M15.5 7L15.219 4.75193C15.0939 3.75107 14.2431 3 13.2344 3L10.7656 3C9.75691 3 8.90611 3.75107 8.78101 4.75193L8.5 7",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

