// Auto-generated by build.rs - DO NOT EDIT
#![allow(non_snake_case, unused_braces)]
use dioxus::prelude::*;

#[component]
pub fn AddCircle(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M7 12L12 12M12 12L17 12M12 12V7M12 12L12 17",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            circle {
                "cx": "12",
                "cy": "12",
                "r": "9",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Add(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M7 12L12 12M12 12L17 12M12 12V7M12 12L12 17",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Backspace(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M7.70015 6.35982L3.53349 11.3598C3.22445 11.7307 3.22445 12.2693 3.53349 12.6402L7.70015 17.6402C7.89015 17.8682 8.1716 18 8.46838 18H18C19.6569 18 21 16.6569 21 15V9C21 7.34315 19.6569 6 18 6H8.46837C8.1716 6 7.89015 6.13182 7.70015 6.35982Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M15 10L13 12M13 12L11 14M13 12L11 10M13 12L15 14",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn CheckBox(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "x": "3",
                "y": "3",
                "width": "18",
                "height": "18",
                "rx": "2",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M7 13L10 16L17 9",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn CheckCircle(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M7 13L10 16L17 9",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            circle {
                "cx": "12",
                "cy": "12",
                "r": "9",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Check(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M7 13L10 16L17 9",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn ClearCircle(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M9 9L15 15",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M15 9L9 15",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            circle {
                "cx": "12",
                "cy": "12",
                "r": "9",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Clear(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M8 8L16 16",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M16 8L8 16",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Extra(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            circle {
                "cx": "12",
                "cy": "6",
                "r": "1.5",
                "transform": "rotate(90 12 6)",
                "fill": "black",
            }
            circle {
                "cx": "12",
                "cy": "12",
                "r": "1.5",
                "transform": "rotate(90 12 12)",
                "fill": "black",
            }
            circle {
                "cx": "12",
                "cy": "18",
                "r": "1.5",
                "transform": "rotate(90 12 18)",
                "fill": "black",
            }
        
        }
    }
}

#[component]
pub fn Filter1(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M17.8258 5H6.17422C5.31987 5 4.85896 6.00212 5.41496 6.65079L9.75926 11.7191C9.91461 11.9004 10 12.1312 10 12.3699V17.382C10 17.7607 10.214 18.107 10.5528 18.2764L12.5528 19.2764C13.2177 19.6088 14 19.1253 14 18.382V12.3699C14 12.1312 14.0854 11.9004 14.2407 11.7191L18.585 6.65079C19.141 6.00212 18.6801 5 17.8258 5Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Filter2(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M20 7H4",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M20 12L10 12",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M20 17H18",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Filter(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M4 7H20",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M7 12L17 12",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M11 17H13",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn RemoveCircle(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M7 12L17 12",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            circle {
                "cx": "12",
                "cy": "12",
                "r": "9",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Remove(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M7 12L17 12",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Sort(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M4 7H20",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M4 12L14 12",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M4 17H6",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Warning(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            circle {
                "cx": "12",
                "cy": "17",
                "r": "1",
                "fill": "black",
            }
            path {
                "d": "M12 10L12 14",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M3.44722 18.1056L10.2111 4.57771C10.9482 3.10361 13.0518 3.10362 13.7889 4.57771L20.5528 18.1056C21.2177 19.4354 20.2507 21 18.7639 21H5.23607C3.7493 21 2.78231 19.4354 3.44722 18.1056Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

