require 'dotenv'
Dotenv.load

default_platform(:ios)

platform :ios do
  desc "Build and deploy iOS app to TestFlight"
  lane :deploy do
    api_key = get_api_key

    build_ios_app(
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key
    )
  end

  private_lane :get_api_key do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_KEY_P8"].gsub("\\n", "\n"),
      is_key_content_base64: false,
      duration: 1200,
      in_house: false
    )
  end
end
