default_platform(:ios)

platform :ios do
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "fastlane/AuthKey_#{ENV['ASC_KEY_ID']}.p8",
      duration: 1200,
      in_house: false
    )

    app_id = ENV["APP_IDENTIFIER"] || "foundation.ratel.app"
    team_id = ENV["APPLE_TEAM_ID"]
    profile_name = ENV["PROFILE_NAME"] || "match AppStore #{app_id}"

    build_ios_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      xcargs: "DEVELOPMENT_TEAM=#{team_id} CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER='#{profile_name}' PRODUCT_BUNDLE_IDENTIFIER=#{app_id}",
      export_options: {
        method: "app-store",
        signingStyle: "manual",
        provisioningProfiles: {
          app_id => profile_name
        }
      }
    )

    upload_to_testflight(api_key: api_key)
  end
end
