// Auto-generated by build.rs - DO NOT EDIT
#![allow(non_snake_case, unused_braces)]
use dioxus::prelude::*;

#[component]
pub fn Formatting(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M13.5498 19.5H15.5498L10.5498 5.5H8.5498L3.5498 19.5H5.5498L6.9498 15.5H12.0498L13.5498 19.5ZM7.64981 13.5L9.5498 8.3L11.4498 13.5H7.64981ZM20.4498 18C20.4498 18.2967 20.3618 18.5867 20.197 18.8334C20.0322 19.08 19.7979 19.2723 19.5238 19.3858C19.2497 19.4993 18.9481 19.5291 18.6572 19.4712C18.3662 19.4133 18.0989 19.2704 17.8891 19.0607C17.6794 18.8509 17.5365 18.5836 17.4786 18.2926C17.4207 18.0017 17.4505 17.7001 17.564 17.426C17.6775 17.1519 17.8698 16.9176 18.1164 16.7528C18.3631 16.588 18.6531 16.5 18.9498 16.5C19.3476 16.5 19.7292 16.658 20.0105 16.9393C20.2918 17.2206 20.4498 17.6022 20.4498 18ZM20.4498 14C20.4498 14.2967 20.3618 14.5867 20.197 14.8334C20.0322 15.08 19.7979 15.2723 19.5238 15.3858C19.2497 15.4994 18.9481 15.5291 18.6572 15.4712C18.3662 15.4133 18.0989 15.2704 17.8891 15.0607C17.6794 14.8509 17.5365 14.5836 17.4786 14.2926C17.4207 14.0017 17.4505 13.7001 17.564 13.426C17.6775 13.1519 17.8698 12.9176 18.1164 12.7528C18.3631 12.588 18.6531 12.5 18.9498 12.5C19.3476 12.5 19.7292 12.658 20.0105 12.9393C20.2918 13.2206 20.4498 13.6022 20.4498 14ZM20.4498 10C20.4498 10.2967 20.3618 10.5867 20.197 10.8334C20.0322 11.08 19.7979 11.2723 19.5238 11.3858C19.2497 11.4994 18.9481 11.5291 18.6572 11.4712C18.3662 11.4133 18.0989 11.2704 17.8891 11.0607C17.6794 10.8509 17.5365 10.5836 17.4786 10.2926C17.4207 10.0017 17.4505 9.70006 17.564 9.42597C17.6775 9.15189 17.8698 8.91762 18.1164 8.7528C18.3631 8.58797 18.6531 8.5 18.9498 8.5C19.3476 8.5 19.7292 8.65804 20.0105 8.93934C20.2918 9.22064 20.4498 9.60218 20.4498 10Z",
                "fill": "#737373",
            }
        
        }
    }
}

#[component]
pub fn ArrDown(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 18 18",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            g { "clip-path": "url(#clip0_4162_114762)",
                path {
                    "d": "M14 7.72701L9.61152 11.7165C9.26477 12.0318 8.73523 12.0318 8.38848 11.7165L4 7.72701",
                    "stroke": "#AEAAAB",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
            }
            defs {
                clipPath { "id": "clip0_4162_114762",
                    rect { "width": "18", "height": "18", "fill": "white" }
                }
            }
        
        }
    }
}

#[component]
pub fn Bold(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M15.2504 12.3C15.74 12.0018 16.1532 11.5934 16.4571 11.1073C16.7609 10.6212 16.9469 10.0708 17.0004 9.5C17.0097 8.98388 16.9172 8.471 16.7282 7.99063C16.5392 7.51027 16.2575 7.07184 15.899 6.70039C15.5406 6.32894 15.1124 6.03174 14.6391 5.82578C14.1658 5.61981 13.6565 5.50911 13.1404 5.5H6.65039V19.5H13.6504C14.1415 19.4948 14.6269 19.3929 15.0786 19.2001C15.5304 19.0073 15.9397 18.7274 16.2833 18.3764C16.6269 18.0253 16.898 17.6101 17.0811 17.1543C17.2642 16.6985 17.3557 16.2112 17.3504 15.72V15.6C17.3507 14.9071 17.1533 14.2285 16.7813 13.644C16.4093 13.0594 15.8782 12.5931 15.2504 12.3ZM8.65039 7.5H12.8504C13.2766 7.48681 13.6966 7.60428 14.0541 7.83665C14.4116 8.06902 14.6894 8.40517 14.8504 8.8C15.0133 9.32779 14.9606 9.89859 14.7039 10.3877C14.4472 10.8767 14.0073 11.2443 13.4804 11.41C13.2758 11.47 13.0636 11.5003 12.8504 11.5H8.65039V7.5ZM13.2504 17.5H8.65039V13.5H13.2504C13.6766 13.4868 14.0966 13.6043 14.4541 13.8367C14.8116 14.069 15.0894 14.4052 15.2504 14.8C15.4133 15.3278 15.3606 15.8986 15.1039 16.3877C14.8472 16.8767 14.4073 17.2443 13.8804 17.41C13.6758 17.47 13.4636 17.5003 13.2504 17.5Z",
                "fill": "#737373",
            }
        
        }
    }
}

#[component]
pub fn Capslock(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 18 15",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M10.5498 14.5H12.5498L7.5498 0.5H5.5498L0.549805 14.5H2.5498L3.9498 10.5H9.0498L10.5498 14.5ZM4.64981 8.5L6.5498 3.3L8.4498 8.5H4.64981ZM17.4498 13C17.4498 13.2967 17.3618 13.5867 17.197 13.8334C17.0322 14.08 16.7979 14.2723 16.5238 14.3858C16.2497 14.4993 15.9481 14.5291 15.6572 14.4712C15.3662 14.4133 15.0989 14.2704 14.8891 14.0607C14.6794 13.8509 14.5365 13.5836 14.4786 13.2926C14.4207 13.0017 14.4505 12.7001 14.564 12.426C14.6775 12.1519 14.8698 11.9176 15.1164 11.7528C15.3631 11.588 15.6531 11.5 15.9498 11.5C16.3476 11.5 16.7292 11.658 17.0105 11.9393C17.2918 12.2206 17.4498 12.6022 17.4498 13ZM17.4498 9C17.4498 9.29667 17.3618 9.58668 17.197 9.83335C17.0322 10.08 16.7979 10.2723 16.5238 10.3858C16.2497 10.4994 15.9481 10.5291 15.6572 10.4712C15.3662 10.4133 15.0989 10.2704 14.8891 10.0607C14.6794 9.85088 14.5365 9.58361 14.4786 9.29264C14.4207 9.00166 14.4505 8.70006 14.564 8.42597C14.6775 8.15189 14.8698 7.91762 15.1164 7.7528C15.3631 7.58797 15.6531 7.5 15.9498 7.5C16.3476 7.5 16.7292 7.65804 17.0105 7.93934C17.2918 8.22064 17.4498 8.60218 17.4498 9ZM17.4498 5C17.4498 5.29667 17.3618 5.58668 17.197 5.83335C17.0322 6.08003 16.7979 6.27229 16.5238 6.38582C16.2497 6.49935 15.9481 6.52906 15.6572 6.47118C15.3662 6.4133 15.0989 6.27044 14.8891 6.06066C14.6794 5.85088 14.5365 5.58361 14.4786 5.29264C14.4207 5.00166 14.4505 4.70006 14.564 4.42597C14.6775 4.15189 14.8698 3.91762 15.1164 3.7528C15.3631 3.58797 15.6531 3.5 15.9498 3.5C16.3476 3.5 16.7292 3.65804 17.0105 3.93934C17.2918 4.22064 17.4498 4.60218 17.4498 5Z",
                "fill": "#737373",
            }
        
        }
    }
}

#[component]
pub fn Codespen(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M9 7.5L4 12.5L9 17.5",
                "stroke": "#737373",
                "stroke-width": "1.5",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M15 7.5L20 12.5L15 17.5",
                "stroke": "#737373",
                "stroke-width": "1.5",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn CommentPasteWhite(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            g { "clip-path": "url(#clip0_4162_114776)",
                path {
                    "d": "M3 6.83325C3 4.62411 4.79086 2.83325 7 2.83325H17C19.2091 2.83325 21 4.62411 21 6.83325V14.8333C21 17.0424 19.2091 18.8333 17 18.8333H14.25L12.8 20.7666C12.4 21.2999 11.6 21.2999 11.2 20.7666L9.75 18.8333H7C4.79086 18.8333 3 17.0424 3 14.8333V6.83325Z",
                    "stroke": "white",
                    "stroke-width": "1.5",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
                path {
                    "d": "M16.3508 14.2735V11.3013C16.3508 10.1967 15.4554 9.3013 14.3508 9.3013H7.64941M7.64941 9.3013L10.1355 6.81519M7.64941 9.3013L10.1355 11.7874",
                    "stroke": "white",
                    "stroke-width": "1.5",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
            }
            defs {
                clipPath { "id": "clip0_4162_114776",
                    rect { "width": "24", "height": "24", "fill": "white" }
                }
            }
        
        }
    }
}

#[component]
pub fn CommentPaste(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            g { "clip-path": "url(#clip0_4162_114791)",
                path {
                    "d": "M3 7.33325C3 5.12411 4.79086 3.33325 7 3.33325H17C19.2091 3.33325 21 5.12411 21 7.33325V15.3333C21 17.5424 19.2091 19.3333 17 19.3333H14.25L12.8 21.2666C12.4 21.7999 11.6 21.7999 11.2 21.2666L9.75 19.3333H7C4.79086 19.3333 3 17.5424 3 15.3333V7.33325Z",
                    "stroke": "#737373",
                    "stroke-width": "1.5",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
                path {
                    "d": "M16.3508 14.7735V11.8013C16.3508 10.6967 15.4554 9.8013 14.3508 9.8013H7.64941M7.64941 9.8013L10.1355 7.31519M7.64941 9.8013L10.1355 12.2874",
                    "stroke": "#737373",
                    "stroke-width": "1.5",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
            }
            defs {
                clipPath { "id": "clip0_4162_114791",
                    rect {
                        "width": "24",
                        "height": "24",
                        "fill": "white",
                        "transform": "translate(0 0.5)",
                    }
                }
            }
        
        }
    }
}

#[component]
pub fn Italics(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M11.7596 9.5H13.7596L11.5596 19.5H9.55957L11.7596 9.5ZM13.4396 5.5C13.2418 5.5 13.0484 5.55865 12.884 5.66853C12.7196 5.77841 12.5914 5.93459 12.5157 6.11732C12.44 6.30004 12.4202 6.50111 12.4588 6.69509C12.4974 6.88907 12.5926 7.06725 12.7325 7.20711C12.8723 7.34696 13.0505 7.4422 13.2445 7.48079C13.4385 7.51937 13.6395 7.49957 13.8223 7.42388C14.005 7.34819 14.1612 7.22002 14.271 7.05557C14.3809 6.89112 14.4396 6.69778 14.4396 6.5C14.4396 6.23478 14.3342 5.98043 14.1467 5.79289C13.9591 5.60536 13.7048 5.5 13.4396 5.5Z",
                "fill": "#737373",
            }
        
        }
    }
}

#[component]
pub fn LinkPasteWhite(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M7.75691 10.5858L4.92848 13.4142C3.75691 14.5858 3.75691 16.4853 4.92848 17.6569L6.3427 19.0711C7.51427 20.2427 9.41377 20.2427 10.5853 19.0711L13.4138 16.2427M9.87824 14.1214L14.1209 9.87873M10.5853 7.7574L13.4137 4.92897C14.5853 3.7574 16.4848 3.7574 17.6564 4.92897L19.0706 6.34319C20.2422 7.51476 20.2422 9.41425 19.0706 10.5858L16.2422 13.4143",
                "stroke": "white",
                "stroke-width": "1.5",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn LinkPaste(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            g { "clip-path": "url(#clip0_4162_114790)",
                path {
                    "d": "M7.75691 11.0858L4.92848 13.9142C3.75691 15.0858 3.75691 16.9853 4.92848 18.1569L6.3427 19.5711C7.51427 20.7427 9.41377 20.7427 10.5853 19.5711L13.4138 16.7427M9.87824 14.6214L14.1209 10.3787M10.5853 8.2574L13.4137 5.42897C14.5853 4.2574 16.4848 4.2574 17.6564 5.42897L19.0706 6.84319C20.2422 8.01476 20.2422 9.91425 19.0706 11.0858L16.2422 13.9143",
                    "stroke": "#737373",
                    "stroke-width": "1.5",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
            }
            defs {
                clipPath { "id": "clip0_4162_114790",
                    rect {
                        "width": "24",
                        "height": "24",
                        "fill": "white",
                        "transform": "translate(0 0.5)",
                    }
                }
            }
        
        }
    }
}

#[component]
pub fn MiscParts(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 32 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M4 11C3.2 11 2.5 11.7 2.5 12.5C2.5 13.3 3.2 14 4 14C4.8 14 5.5 13.3 5.5 12.5C5.5 11.7 4.8 11 4 11ZM4 6C3.2 6 2.5 6.7 2.5 7.5C2.5 8.3 3.2 9 4 9C4.8 9 5.5 8.3 5.5 7.5C5.5 6.7 4.8 6 4 6ZM4 16C3.2 16 2.5 16.7 2.5 17.5C2.5 18.3 3.2 19 4 19C4.8 19 5.5 18.3 5.5 17.5C5.5 16.7 4.8 16 4 16ZM7.5 6.5V8.5H21.5V6.5H7.5ZM7.5 18.5H21.5V16.5H7.5V18.5ZM7.5 13.5H21.5V11.5H7.5V13.5Z",
                "fill": "#737373",
            }
            path { "d": "M28 15L32 10H24L28 15Z", "fill": "#737373" }
        
        }
    }
}

#[component]
pub fn Misc2Part(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 32 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M2.5 16.5H4.5V17H3.5V18H4.5V18.5H2.5V19.5H5.5V15.5H2.5V16.5ZM3.5 9.5H4.5V5.5H2.5V6.5H3.5V9.5ZM2.5 11.5H4.3L2.5 13.6V14.5H5.5V13.5H3.7L5.5 11.4V10.5H2.5V11.5ZM7.5 6.5V8.5H21.5V6.5H7.5ZM7.5 18.5H21.5V16.5H7.5V18.5ZM7.5 13.5H21.5V11.5H7.5V13.5Z",
                "fill": "#737373",
            }
            path { "d": "M28 15L32 10H24L28 15Z", "fill": "#737373" }
        
        }
    }
}

#[component]
pub fn Misc3Part(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 32 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M3 18.5H9V16.5H3V18.5ZM3 11.5V13.5H15V11.5H3ZM3 6.5V8.5H21V6.5H3Z",
                "fill": "#737373",
            }
            path { "d": "M28 15L32 10H24L28 15Z", "fill": "#737373" }
        
        }
    }
}

#[component]
pub fn Paint(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 15",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M7.91756 7.74093L15.6655 2.35076L16.8449 3.64667L10.7509 10.8541L7.91756 7.74093ZM5.58746 8.15211L10.1228 13.1354C10.2167 13.2284 10.3292 13.3004 10.453 13.3467C10.5768 13.393 10.709 13.4125 10.8409 13.4039C10.9728 13.3953 11.1013 13.3588 11.2181 13.2969C11.3348 13.2349 11.4371 13.1489 11.5181 13.0445L18.9695 4.23151C19.1179 4.0684 19.202 3.85684 19.2059 3.63632C19.2098 3.41581 19.1333 3.2014 18.9908 3.03311L16.4778 0.271948C16.3236 0.114225 16.1174 0.0179803 15.8975 0.00117661C15.6775 -0.015627 15.459 0.048158 15.2827 0.180628L5.80905 6.77146C5.69748 6.84232 5.60223 6.93605 5.52958 7.04646C5.45693 7.15686 5.40853 7.28143 5.38759 7.41192C5.36664 7.54242 5.37363 7.67587 5.40808 7.80347C5.44254 7.93106 5.50367 8.04989 5.58746 8.15211ZM0.793945 14.0278L6.4113 15.0001L7.89044 13.6539L4.86155 10.3259L0.793945 14.0278Z",
                "fill": "#737373",
            }
        
        }
    }
}

#[component]
pub fn Paint2(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 14 19",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M10.1996 8.994C10.1996 8.994 6.59961 12.894 6.59961 15.294C6.59304 15.7733 6.68095 16.2493 6.85831 16.6946C7.03568 17.14 7.29902 17.546 7.63331 17.8896C8.30845 18.5835 9.23157 18.9807 10.1996 18.994C11.1677 19.0073 12.1013 18.6354 12.7952 17.9603C13.1388 17.626 13.4131 17.2273 13.6026 16.787C13.7921 16.3467 13.893 15.8733 13.8996 15.394V15.294C13.8996 12.894 10.1996 8.994 10.1996 8.994ZM8.72961 7.637L9.39861 6.913L7.09961 0.5H5.09961L0.0996094 14.5H2.09961L3.52961 10.5H6.47261C7.15129 9.49091 7.90439 8.53392 8.72561 7.637H8.72961ZM6.09961 3.3L7.95961 8.5H4.24361L6.09961 3.3Z",
                "fill": "#737373",
            }
        
        }
    }
}

#[component]
pub fn ParagraphLight(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            g { "opacity": "0.25",
                path {
                    "d": "M3 12.5L6 15.5V9.5L3 12.5ZM3 19.5H21V17.5H3V19.5ZM3 7.5H21V5.5H3V7.5ZM9 11.5H21V9.5H9V11.5ZM9 15.5H21V13.5H9V15.5Z",
                    "fill": "#737373",
                }
            }
        
        }
    }
}

#[component]
pub fn Paragraph(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M3 9.5V15.5L6 12.5L3 9.5ZM3 19.5H21V17.5H3V19.5ZM3 7.5H21V5.5H3V7.5ZM9 11.5H21V9.5H9V11.5ZM9 15.5H21V13.5H9V15.5Z",
                "fill": "#737373",
            }
        
        }
    }
}

#[component]
pub fn Repost(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M3 7.52344C3 5.3143 4.79086 3.52344 7 3.52344H17C19.2091 3.52344 21 5.3143 21 7.52344V15.5234C21 17.7326 19.2091 19.5234 17 19.5234H14.25L12.8 21.4568C12.4 21.9901 11.6 21.9901 11.2 21.4568L9.75 19.5234H7C4.79086 19.5234 3 17.7326 3 15.5234V7.52344Z",
                "stroke": "#171717",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            line {
                "x-1": "8",
                "y-1": "7.14844",
                "x-2": "16",
                "y-2": "7.14844",
                "stroke": "#171717",
                "stroke-width": "2",
                "stroke-linecap": "round",
            }
            path {
                "d": "M7.5 11.5859L13.4062 11.5859",
                "stroke": "#171717",
                "stroke-width": "2",
                "stroke-linecap": "round",
            }
            path {
                "d": "M7.5 15.2749H10.5",
                "stroke": "#171717",
                "stroke-width": "2",
                "stroke-linecap": "round",
            }
        
        }
    }
}

#[component]
pub fn ShapeArrowDown(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 21",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M10.0001 12.7223L5.55566 8.27783L14.4446 8.27783L10.0001 12.7223Z",
                "fill": "#777677",
                "stroke": "#777677",
                "stroke-width": "1.5",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn Strike(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M3 12.7031H21V14.2031H16.6342C16.8711 14.7003 16.9906 15.2452 16.9836 15.796C16.9977 16.3184 16.8855 16.8366 16.6567 17.3066C16.428 17.7765 16.0893 18.1844 15.6694 18.4957C14.6579 19.2073 13.4378 19.5609 12.2025 19.5001C11.3 19.5062 10.4062 19.3226 9.57916 18.9611C8.82387 18.6478 8.16917 18.133 7.68652 17.4729C7.24212 16.8428 7.00762 16.0886 7.01636 15.3175V15.2041H7.30359V15.203H7.64508V15.2041H9.02V15.3175C9.00433 15.6688 9.07382 16.0188 9.22253 16.3376C9.37125 16.6563 9.59479 16.9344 9.87413 17.1481C10.5515 17.6304 11.372 17.8698 12.2025 17.8274C12.9356 17.8753 13.6645 17.6836 14.2792 17.2812C14.507 17.1127 14.6901 16.8909 14.8124 16.6352C14.9346 16.3796 14.9923 16.0978 14.9804 15.8147C14.9964 15.5411 14.9459 15.2677 14.8332 15.018C14.7205 14.7682 14.5491 14.5494 14.3335 14.3803C14.2451 14.3162 14.1533 14.2571 14.0585 14.203H3V12.7031ZM16.3447 7.55992C15.9232 6.90493 15.3271 6.3807 14.6236 6.04631C13.8394 5.67272 12.9793 5.48577 12.1107 5.50011C10.8996 5.44813 9.70883 5.82415 8.74719 6.56224C8.33435 6.88109 8.00134 7.29159 7.77448 7.76131C7.54762 8.23103 7.43313 8.74708 7.44006 9.26866C7.43656 9.76295 7.54659 10.2515 7.76166 10.6965H10.3583C10.275 10.6429 10.173 10.5908 10.1056 10.5359C9.90219 10.3858 9.73702 10.1898 9.62358 9.96385C9.51014 9.73789 9.45164 9.48835 9.45282 9.23552C9.43773 8.94691 9.49242 8.65892 9.61226 8.39593C9.73209 8.13294 9.91354 7.9027 10.1412 7.72472C10.7173 7.32519 11.4109 7.13065 12.1107 7.17229C12.8717 7.12391 13.6231 7.36251 14.2167 7.84099C14.465 8.07478 14.6594 8.35979 14.7865 8.67624C14.9136 8.99269 14.9703 9.33301 14.9527 9.67357V9.78698H16.9559V9.67357C16.9592 8.92497 16.7471 8.19122 16.3447 7.55992Z",
                "fill": "#737373",
            }
        
        }
    }
}

#[component]
pub fn TabeCells(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M20 5.5H4C2.9 5.5 2 6.4 2 7.5V9.5V11V14V15.5V17.5C2 18.6 2.9 19.5 4 19.5H20C21.1 19.5 22 18.6 22 17.5V15.5V14V11V9.5V7.5C22 6.4 21.1 5.5 20 5.5ZM9.5 14V11H14.5V14H9.5ZM14.5 15.5V18H9.5V15.5H14.5ZM9.5 9.5V7H14.5V9.5H9.5ZM3.5 7.5C3.5 7.2 3.7 7 4 7H8V9.5H3.5V7.5ZM3.5 11H8V14H3.5V11ZM3.5 17.5V15.5H8V18H4C3.7 18 3.5 17.8 3.5 17.5ZM20.5 17.5C20.5 17.8 20.3 18 20 18H16V15.5H20.5V17.5ZM20.5 14H16V11H20.5V14ZM16 9.5V7H20C20.3 7 20.5 7.2 20.5 7.5V9.5H16Z",
                "fill": "#737373",
            }
        
        }
    }
}

#[component]
pub fn Underline(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M19 20.5V22.5H5V20.5H19ZM16 13.715C15.9671 14.375 15.7711 15.0165 15.4297 15.5823C15.0883 16.1481 14.6121 16.6205 14.0435 16.9572C13.475 17.294 12.8318 17.4847 12.1716 17.5122C11.5114 17.5397 10.8546 17.4033 10.26 17.115C9.57464 16.8185 8.99341 16.3241 8.59077 15.6952C8.18813 15.0663 7.98242 14.3315 8 13.585V5.505H6V13.715C6.03383 14.6564 6.28885 15.5766 6.74442 16.4012C7.19998 17.2257 7.84329 17.9314 8.62227 18.4611C9.40125 18.9908 10.294 19.3296 11.2283 19.4502C12.1625 19.5707 13.1121 19.4696 14 19.155C15.1811 18.7613 16.2059 18.0012 16.9252 16.985C17.6446 15.9689 18.0211 14.7498 18 13.505V5.505H16V13.715ZM16 5.5H18H16ZM8 5.5H6H8Z",
                "fill": "#737373",
            }
        
        }
    }
}

#[component]
pub fn UploadImage(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 25",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            g { "clip-path": "url(#clip0_4162_114789)",
                path {
                    "d": "M13 4.5H8.8C7.11984 4.5 6.27976 4.5 5.63803 4.82698C5.07354 5.1146 4.6146 5.57354 4.32698 6.13803C4 6.77976 4 7.61984 4 9.3V15.7C4 17.3802 4 18.2202 4.32698 18.862C4.6146 19.4265 5.07354 19.8854 5.63803 20.173C6.27976 20.5 7.11984 20.5 8.8 20.5H15.2C16.8802 20.5 17.7202 20.5 18.362 20.173C18.9265 19.8854 19.3854 19.4265 19.673 18.862C20 18.2202 20 17.3802 20 15.7V11.5",
                    "stroke": "#737373",
                    "stroke-width": "1.5",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
                path {
                    "d": "M4 16.5L8.29289 12.2071C8.68342 11.8166 9.31658 11.8166 9.70711 12.2071L13 15.5M13 15.5L15.7929 12.7071C16.1834 12.3166 16.8166 12.3166 17.2071 12.7071L20 15.5M13 15.5L15.25 17.75",
                    "stroke": "#737373",
                    "stroke-width": "1.5",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
                path {
                    "d": "M18.5 3.5V6M18.5 8.5V6M18.5 6H16M18.5 6H21",
                    "stroke": "#737373",
                    "stroke-width": "1.5",
                    "stroke-linecap": "round",
                    "stroke-linejoin": "round",
                }
            }
            defs {
                clipPath { "id": "clip0_4162_114789",
                    rect {
                        "width": "24",
                        "height": "24",
                        "fill": "white",
                        "transform": "translate(0 0.5)",
                    }
                }
            }
        
        }
    }
}

