use crate::common::*;

/// Body for `POST /api/cross-posting/connections/bluesky`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectBlueskyRequest {
    /// Bluesky handle, e.g. `user.bsky.social`. May also be the user's DID.
    pub handle: String,
    /// Bluesky **app password** (NOT the account password). Generated by the
    /// user at <https://bsky.app/settings/app-passwords>. Format
    /// `xxxx-xxxx-xxxx-xxxx`. Used once to mint a session, then discarded.
    pub app_password: String,
}

/// Body for `PATCH /api/cross-posting/connections/{platform}`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToggleAutoPostRequest {
    pub auto_post_enabled: bool,
}
