use crate::common::*;

/// Body for `POST /api/cross-posting/connections/bluesky`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectBlueskyRequest {
    /// Bluesky handle, e.g. `user.bsky.social`. May also be the user's DID.
    pub handle: String,
    /// Bluesky **app password** (NOT the account password). Generated by the
    /// user at <https://bsky.app/settings/app-passwords>. Format
    /// `xxxx-xxxx-xxxx-xxxx`. Used once to mint a session, then discarded.
    pub app_password: String,
}

/// Body for `PATCH /api/cross-posting/connections/{platform}`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToggleAutoPostRequest {
    pub auto_post_enabled: bool,
}

/// Body for `POST /api/cross-posting/connections/linkedin/init`. The
/// optional `return_to` is a same-origin SPA path the OAuth callback
/// should bounce the user back to after a successful connection —
/// typically the post-edit page they came from. Omit (or send `null`)
/// to use the default `/{username}/settings/connections` destination.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LinkedInOauthInitRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub return_to: Option<String>,
}
