// Auto-generated by build.rs - DO NOT EDIT
#![allow(non_snake_case, unused_braces)]
use dioxus::prelude::*;

#[component]
pub fn AddColumnAfter(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 20",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "x": "3",
                "y": "3",
                "width": "10",
                "height": "14",
                "rx": "1",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "fill": "none",
            }
            line {
                "x-1": "8",
                "y-1": "3",
                "x-2": "8",
                "y-2": "17",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "3",
                "y-1": "10",
                "x-2": "13",
                "y-2": "10",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "14",
                "y-1": "10",
                "x-2": "17",
                "y-2": "10",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "15.5",
                "y-1": "8",
                "x-2": "15.5",
                "y-2": "12",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
        
        }
    }
}

#[component]
pub fn AddColumnBefore(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 20",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "x": "7",
                "y": "3",
                "width": "10",
                "height": "14",
                "rx": "1",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "fill": "none",
            }
            line {
                "x-1": "12",
                "y-1": "3",
                "x-2": "12",
                "y-2": "17",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "7",
                "y-1": "10",
                "x-2": "17",
                "y-2": "10",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "3",
                "y-1": "10",
                "x-2": "6",
                "y-2": "10",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "4.5",
                "y-1": "8",
                "x-2": "4.5",
                "y-2": "12",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
        
        }
    }
}

#[component]
pub fn AddRowAfter(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 20",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "x": "3",
                "y": "3",
                "width": "14",
                "height": "10",
                "rx": "1",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "fill": "none",
            }
            line {
                "x-1": "3",
                "y-1": "8",
                "x-2": "17",
                "y-2": "8",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "10",
                "y-1": "3",
                "x-2": "10",
                "y-2": "13",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "10",
                "y-1": "14",
                "x-2": "10",
                "y-2": "17",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "8",
                "y-1": "15.5",
                "x-2": "12",
                "y-2": "15.5",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
        
        }
    }
}

#[component]
pub fn AddRowBefore(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 20",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "x": "3",
                "y": "7",
                "width": "14",
                "height": "10",
                "rx": "1",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "fill": "none",
            }
            line {
                "x-1": "3",
                "y-1": "12",
                "x-2": "17",
                "y-2": "12",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "10",
                "y-1": "7",
                "x-2": "10",
                "y-2": "17",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "10",
                "y-1": "3",
                "x-2": "10",
                "y-2": "6",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "8",
                "y-1": "4.5",
                "x-2": "12",
                "y-2": "4.5",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
        
        }
    }
}

#[component]
pub fn DeleteColumn(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 20",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "x": "3",
                "y": "3",
                "width": "14",
                "height": "14",
                "rx": "1",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "fill": "none",
            }
            line {
                "x-1": "7",
                "y-1": "3",
                "x-2": "7",
                "y-2": "17",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "13",
                "y-1": "3",
                "x-2": "13",
                "y-2": "17",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "3",
                "y-1": "10",
                "x-2": "17",
                "y-2": "10",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "10",
                "y-1": "7",
                "x-2": "10",
                "y-2": "13",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
        
        }
    }
}

#[component]
pub fn DeleteRow(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 20",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "x": "3",
                "y": "3",
                "width": "14",
                "height": "14",
                "rx": "1",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "fill": "none",
            }
            line {
                "x-1": "3",
                "y-1": "7",
                "x-2": "17",
                "y-2": "7",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "3",
                "y-1": "13",
                "x-2": "17",
                "y-2": "13",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "10",
                "y-1": "3",
                "x-2": "10",
                "y-2": "17",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "7",
                "y-1": "10",
                "x-2": "13",
                "y-2": "10",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
        
        }
    }
}

#[component]
pub fn DeleteTable(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 20",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "x": "3",
                "y": "3",
                "width": "14",
                "height": "14",
                "rx": "1",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "fill": "none",
            }
            line {
                "x-1": "3",
                "y-1": "7",
                "x-2": "17",
                "y-2": "7",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "3",
                "y-1": "11",
                "x-2": "17",
                "y-2": "11",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "10",
                "y-1": "3",
                "x-2": "10",
                "y-2": "17",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "6",
                "y-1": "6",
                "x-2": "14",
                "y-2": "14",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "14",
                "y-1": "6",
                "x-2": "6",
                "y-2": "14",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
        
        }
    }
}

#[component]
pub fn InsertTable(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 20",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "x": "3",
                "y": "3",
                "width": "14",
                "height": "14",
                "rx": "1",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "fill": "none",
            }
            line {
                "x-1": "3",
                "y-1": "7",
                "x-2": "17",
                "y-2": "7",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "3",
                "y-1": "11",
                "x-2": "17",
                "y-2": "11",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            line {
                "x-1": "10",
                "y-1": "3",
                "x-2": "10",
                "y-2": "17",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
        
        }
    }
}

#[component]
pub fn MergeCells(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 20",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "x": "3",
                "y": "6",
                "width": "14",
                "height": "8",
                "rx": "1",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "fill": "none",
            }
            path {
                "d": "M7 10L9 10",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "stroke-linecap": "round",
            }
            path {
                "d": "M11 10L13 10",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "stroke-linecap": "round",
            }
            path {
                "d": "M9.5 8.5L8 10L9.5 11.5",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
                "fill": "none",
            }
            path {
                "d": "M10.5 8.5L12 10L10.5 11.5",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
                "fill": "none",
            }
        
        }
    }
}

#[component]
pub fn SplitCell(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 20 20",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "x": "3",
                "y": "6",
                "width": "14",
                "height": "8",
                "rx": "1",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "fill": "none",
            }
            line {
                "x-1": "10",
                "y-1": "6",
                "x-2": "10",
                "y-2": "14",
                "stroke": "currentColor",
                "stroke-width": "1.5",
            }
            path {
                "d": "M9 8L7.5 10L9 12",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
                "fill": "none",
            }
            path {
                "d": "M11 8L12.5 10L11 12",
                "stroke": "currentColor",
                "stroke-width": "1.5",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
                "fill": "none",
            }
        
        }
    }
}

