// Auto-generated by build.rs - DO NOT EDIT
#![allow(non_snake_case, unused_braces)]
use dioxus::prelude::*;

#[component]
pub fn Kr(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 72 72",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "width": "72",
                "height": "72",
                "fill": "url(#pattern0_6944_16121)",
            }
            defs {
                pattern {
                    "id": "pattern0_6944_16121",
                    "pattern-content-units": "objectBoundingBox",
                    "width": "1",
                    "height": "1",
                    r#use {
                        "href": "#image0_6944_16121",
                        "transform": "scale(0.0138889)",
                    }
                }
                image {
                    "id": "image0_6944_16121",
                    "width": "72",
                    "height": "72",
                    "preserve-aspect-ratio": "none",
                    "href": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAMAAABiM0N1AAAAmVBMVEX///8VFRb8/PyJiYn5+fkKCgt4eHkAR6DNLjoAAAHU1NQ1NTb08vPh4uTs7e7MzMyamppNTU7p5uakpKSxsbFCQkMqKiszbLN4Omba2trgfINaWlvZXWdeXl/US1VmkcZgPnNUVFWXtNnrqq8wQolRgr64MUWaNFNkZGXvub2rwuBOPXkTRZfExMTe3t7Bmq+knLuitc6pnKSkH2OTAAAACXBIWXMAAAsTAAALEwEAmpwYAAACqElEQVR4nO1X2ZKCMBAMkBAGucQDFlHE+1p3///rtkAEEhKOLfdly36y1DTT6TDTQeiNN/47XPc1/8dz0Ifw6DDHkh9goZp9aUx1AeIHfwIojga6+CkcsEY0RwH4FAqD6QcBYluoE5ZNgHxMQSROB1iqMwDPV7qKwppiewAjdSkQVwiDGRoDeO1EHsAYzQAycXNHJmwCMOqoSB0BTGwFiDnVsYtlwoB0OmcSKMRhnRVXCUsBtC4ehLRM3BhAs1jnWoRZ2yiK4yja+ry4aV4865xMGN7GRonVtvYEk+jYajgnE3ZeVTQ51bn6zcb6Q1z9WKZ1YWpZTmQ0EFVFpZlzxbFMn0v0UyaaFWZx5TwQW3Xn/FzcqX6A8zOWVVrWI+QxjBjzzrGnV9UU1jEJj2FEdecmgvfJYoR9yXgM48yIE7zhqkYqYQc50aq0Q9pzzPIv33IeoyqpRxdctxHFqDfsViKjR+crsLk2Vx/DdXh8fNz2Jkp2PE14oxluIXMCOrGnnGtX+sTuMIQooOwmhSUPpbshux1QepTwUBoOINpTejtKeOhtAFGSLVg/9ulQ7U+BY/892hTbsV5fdzwNpWF/+53m6hpCpn23I6AtCDuXVy9toU2Mr46XlmkjLSXtOtoI29gucqLv1sbWaLV7GU/CJQCuKK/IIZ3iArb5Z1O1Xs5jzjrMOBIyBYJxtCyLWogHZCLQhYUDclF850pG9oUrKrhwI7sIW+AyeXYGMGHEIYQ3gZgGmeSEcS6AybZ5rLlnAaMRa+xNsg+CfbJxGrEGY70RSHNxPtaHBa2T5TPCnuLQkndOBrNwLEV89HuKA3LvG0bvuWMniwujrHPd8Tgt43FjyD2d85w+gd3Pj6LwNvKyKwRyf3Opcf/ymoVedvFDr7qKvvHGP8IPz0FGDtZW12EAAAAASUVORK5CYII=",
                }
            }
        
        }
    }
}

#[component]
pub fn Us(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 72 72",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            rect {
                "width": "72",
                "height": "72",
                "fill": "url(#pattern0_6944_16122)",
            }
            defs {
                pattern {
                    "id": "pattern0_6944_16122",
                    "pattern-content-units": "objectBoundingBox",
                    "width": "1",
                    "height": "1",
                    r#use {
                        "href": "#image0_6944_16122",
                        "transform": "scale(0.0138889)",
                    }
                }
                image {
                    "id": "image0_6944_16122",
                    "width": "72",
                    "height": "72",
                    "preserve-aspect-ratio": "none",
                    "href": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAMAAABiM0N1AAAAVFBMVEUZL13Rd3zLaG0+UHfgoqbZjZEhN2P///+9PUTEUVhWSWkrP2lpeJaJlaxZaIpKXIA1SHB6h6Kdprrj5uzQ1d6wuMi/xdIyMVnTfYLovb/JYmf09fed3V51AAAACXBIWXMAAAsTAAALEwEAmpwYAAADCElEQVR4nO1W2XLcIBCcBAfW4T43Cf//nymYGdmWjZS49OTarn3oWqHW0PQAAJ/C/bbH/Fvz8/cE5IfPFkKJR9tAJHoizhAJloXqSkg3led7sqrsJrG9RxTsHQVMVnV+ThRVxKIiUxJ+S5RG1edCny+Zqm1ZUNUlrqYmYIzRAEISCTroSXTQAV2ZzzSPDr/32EzV6bUHb0lioy1VBULtwWNdVnUO91mVaXkoCmejN+uS6uZMCGqZgwFSQ58hNirSFaotsIcrofHhAOEVCZKIDESmM3L8L1ZC2jc/JyN9NXMy0qeIboiYMFHCVD/XL/ji9cdCMqmCbkZyBYzq+L7v5IrICmcs6wjUIkeJzUhsRm0YH9kqhb0m8tAmu8qRnA3l35Dxe01gPhNMFr02PWhuzk+44nD5mWjXyDpXuQfXQrqwB03RRBN1F1j20LCHB0KQLGUtWc6RpYY3lqQ9ewjhaQ8cyVN3TLwmotk66dgxs8yRzRa3kVhwaWRsFeszlXLuUom4jdhsxSLZRlHFXhV0JaiMrujccfllUeRzUnbVIsaRGc4QEdGSkKWIgzWUo+jiYdPOqZ8Rx3vyWsin/OLBrGZYhy0YMzUcewhwf95jK6gp3kYoUBA5UE7R7iHYw6McWc8eeJqJ8aToPFnnnT0WohcADHuAzTEbBRByMyoujyObE/aSzRXfi6VRjto4M4ZyLVhNsN2G1TbCZgg2Qys6hWTutPEXxTkYOdI/9phfE5sZRIQzlCPj6P3oKZBGmOMcxX8gRp/nqGb0QKSOx5hO/cU6T6S58+PopZdofeIwY8BxLwbFJ/lCaJRixkK/JRq3F3CBiBcjH3IttJ3W1KojjEQ8x0dv15ox+v5nj3kk94JmpE7Hrc2ZcpQzCrjS8RYVmmqrHLnMOcqUI3l0rcnLa42XNBHBJGhBORLjWoODSMiP0+mgaf8P9/dCPz+HX3uAugjwEDoFfLsIcLsI8IWFvl8EUBcBHkKngB8XAS7L0e3rCj1fBFAXAR5Cp4CniwCX5ej2ELqdePQX+dR/cj3FIWUAAAAASUVORK5CYII=",
                }
            }
        
        }
    }
}

