[application]
name = "main"
default_platform = "web"

[web.app]
title = ""

[web.watcher]
reload_html = true
watch_path = ["src", "../../packages", "public"]

[web.resource.dev]
script = []
