import { test, expect } from "@playwright/test";
import { click, fill, goto, getLocator, getEditor } from "../utils";

/**
 * Team Draft Timeline — E2E
 *
 * Verifies the TeamDraftTimeline component on the team home page (issue #1310).
 * The component shows a horizontal row of draft post cards for team members
 * with TeamAdmin or TeamEdit permissions.
 *
 * Test flow:
 *   1. Create a new team (creator gets TeamAdmin permissions)
 *   2. Create a draft post from the team home page (via Create button)
 *   3. Navigate back to team home and verify the TeamDraftTimeline section
 *      appears with the correct heading and at least one draft card
 *   4. Verify draft card content (Draft badge, title, timestamp)
 *   5. Click a draft card and verify navigation to the post edit page
 *
 * NOTE: Authenticated tests rely on `user.json` generated by auth-setup.
 *       The pre-authenticated user (hi+user1@biyard.co) is used as the team creator.
 *
 * Test IDs / aria-labels used:
 *   - data-testid="team-draft-timeline"       — section container
 *   - aria-label="Scroll Team Drafts left"    — scroll left button
 *   - aria-label="Scroll Team Drafts right"   — scroll right button
 *   - data-testid="team-nickname-input"       — team creation form
 *   - data-testid="team-username-input"       — team creation form
 *   - data-testid="team-description-input"    — team creation form
 */

test.describe.serial("Team draft timeline on team home page", () => {
  const uniqueId = `${Date.now()}${Math.random().toString(36).slice(2, 6)}`;
  const teamNickname = `Draft Team ${uniqueId}`;
  const teamUsername = `e2e_draft_${uniqueId}`;
  const postTitle = `Draft Post for Timeline Test ${uniqueId}`;

  let teamHomeUrl;

  // --- 1. Create a team ---

  test("Create a team to get TeamAdmin permissions", async ({ page }) => {
    await goto(page, "/");

    // Open profile dropdown
    await click(page, { label: "User Profile" });

    // Click "Create Team" in the dropdown
    await click(page, { text: "Create Team" });

    // Fill in team creation form
    const nicknameInput = page.locator('[data-testid="team-nickname-input"]');
    await nicknameInput.fill(teamNickname);

    const usernameInput = page.locator('[data-testid="team-username-input"]');
    await usernameInput.fill(teamUsername);

    const descInput = page.locator('[data-testid="team-description-input"]');
    await descInput.fill("E2E test team for draft timeline");

    // Submit the form
    await click(page, { text: "Create" });

    // Wait for navigation to team home page
    await page.waitForURL(new RegExp(`/${teamUsername}/home`), {
      waitUntil: "load",
    });

    teamHomeUrl = `/${teamUsername}/home`;

    // Verify we are on the team home page
    await expect(page).toHaveURL(new RegExp(`/${teamUsername}/home`));
  });

  // --- 2. Create a draft post from the team home page ---

  test("Create a draft post for the team", async ({ page }) => {
    await goto(page, teamHomeUrl);

    // Click the Create button on the team home page
    await click(page, { text: "Create" });

    // Wait for post edit page to load
    await page.waitForURL(/\/posts\/.*\/edit/, {
      waitUntil: "load",
    });

    // Fill in the title (post is saved as draft automatically)
    await fill(page, { placeholder: "Title" }, postTitle);

    // Fill in the post body using the rich text editor
    const editor = await getEditor(page);
    await editor.fill(
      "This is a draft post created for the TeamDraftTimeline E2E test. " +
        "It should appear in the team draft timeline section on the team home page."
    );

    // Wait for autosave to complete — the editor debounces saves by 3 seconds,
    // then shows "All changes saved" when the server responds successfully.
    await expect(page.getByText("All changes saved")).toBeVisible({ timeout: 15000 });

    // Verify we are on the post edit page
    await expect(page).toHaveURL(/\/posts\/.*\/edit/);
  });

  // --- 3. Verify the TeamDraftTimeline section appears on team home ---

  test("Team draft timeline section is visible on team home page", async ({
    page,
  }) => {
    await goto(page, teamHomeUrl);

    // The TeamDraftTimeline section should be visible for the team creator
    const draftTimeline = await getLocator(page, {
      testId: "team-draft-timeline",
    });
    await expect(draftTimeline).toBeVisible();

    // The section should contain the "Drafts" heading
    await expect(draftTimeline).toContainText("Drafts");
  });

  // --- 4. Verify draft card content ---

  test("Draft card displays title and Draft badge", async ({ page }) => {
    await goto(page, teamHomeUrl);

    // Verify the draft timeline section is visible
    const draftTimeline = await getLocator(page, {
      testId: "team-draft-timeline",
    });
    await expect(draftTimeline).toBeVisible();

    // The draft card should display the post title
    await expect(draftTimeline).toContainText(postTitle);

    // The draft card should display a "Draft" status badge
    await expect(draftTimeline).toContainText("Draft");
  });

  // --- 5. Click a draft card and verify navigation to the edit page ---

  test("Clicking a draft card navigates to the post edit page", async ({
    page,
  }) => {
    await goto(page, teamHomeUrl);

    // Verify the draft timeline section is visible
    const draftTimeline = await getLocator(page, {
      testId: "team-draft-timeline",
    });
    await expect(draftTimeline).toBeVisible();

    // Click the draft card containing the post title
    // The card is a div with cursor-pointer that navigates to /posts/{pk}/edit
    await draftTimeline.getByText(postTitle).click();
    await page.waitForLoadState("load");

    // Verify navigation to the post edit page
    await expect(page).toHaveURL(/\/posts\/.*\/edit/);

    // Verify the post title is in the editor
    const titleInput = page.getByPlaceholder("Title");
    await expect(titleInput).toBeVisible();
    await expect(titleInput).toHaveValue(postTitle);
  });
});
