import { test, expect } from "@playwright/test";
import { click, fill, goto, getEditor } from "../utils";

/**
 * Team Draft Timeline — E2E
 *
 * Verifies the TeamDraftTimeline component on the team home page (issue #1310).
 * The component shows a horizontal row of draft post cards for team members
 * with TeamAdmin or TeamEdit permissions.
 *
 * Test flow:
 *   1. Create a new team (creator gets TeamAdmin permissions)
 *   2. Create a draft post from the team home page (via Create button)
 *   3. Navigate back to team home and verify the TeamDraftTimeline section
 *      appears with the correct heading and at least one draft card
 *   4. Verify draft card content (Draft badge, title, timestamp)
 *   5. Click a draft card and verify navigation to the post edit page
 *
 * NOTE: Authenticated tests rely on `user.json` generated by auth-setup.
 *       The pre-authenticated user (hi+user1@biyard.co) is used as the team creator.
 *
 * Test IDs / aria-labels used:
 *   - data-testid="team-draft-timeline"       — section container
 *   - aria-label="Scroll Team Drafts left"    — scroll left button
 *   - aria-label="Scroll Team Drafts right"   — scroll right button
 *   - data-testid="team-nickname-input"       — team creation form
 *   - data-testid="team-username-input"       — team creation form
 *   - data-testid="team-description-input"    — team creation form
 */

test.describe.serial("Team draft timeline on team home page", () => {
  const uniqueId = `${Date.now()}${Math.random().toString(36).slice(2, 6)}`;
  const teamNickname = `Draft Team ${uniqueId}`;
  const teamUsername = `e2e_draft_${uniqueId}`;
  const postTitle = `Draft Post for Timeline Test ${uniqueId}`;

  let teamHomeUrl;

  // --- 1. Create a team ---
  // The renewed home arena no longer exposes a profile-dropdown "Create Team"
  // affordance, so team creation is driven via the REST API (the same endpoint
  // the UI form submits to). This keeps this scenario focused on the draft
  // timeline itself rather than the orthogonal team-creation UI.

  test("Create a team to get TeamAdmin permissions", async ({ page }) => {
    const res = await page.request.post("/api/teams/create", {
      data: {
        body: {
          username: teamUsername,
          nickname: teamNickname,
          profile_url: "",
          description: "E2E test team for draft timeline",
        },
      },
    });
    expect(res.ok(), `create team: ${await res.text()}`).toBeTruthy();

    teamHomeUrl = `/${teamUsername}/home`;

    await goto(page, teamHomeUrl);
    await expect(page).toHaveURL(new RegExp(`/${teamUsername}/home`));
  });

  // --- 2. Create a draft post from the team home page ---

  test("Create a draft post for the team", async ({ page }) => {
    await goto(page, teamHomeUrl);

    // Wait for the team arena layout to hydrate and propagate the owner
    // role into the arena context before clicking the Create Post button.
    await expect(page.getByTestId("team-home-create-post")).toBeVisible({
      timeout: 15000,
    });

    // Click the Create Post button on the team home page
    await click(page, { testId: "team-home-create-post" });

    // Wait for post edit page to load
    await page.waitForURL(/\/posts\/.*\/edit/, {
      waitUntil: "load",
    });

    // Fill in the title (post is saved as draft automatically)
    await fill(page, { placeholder: "Title your post…" }, postTitle);

    // Fill in the post body using the rich text editor
    const editor = await getEditor(page);
    await editor.fill(
      "This is a draft post created for the TeamDraftTimeline E2E test. " +
        "It should appear in the team draft timeline section on the team home page."
    );

    // Wait for autosave to complete — the editor debounces saves by 3 seconds,
    // then shows "All changes saved" when the server responds successfully.
    await expect(page.getByText("All changes saved")).toBeVisible({ timeout: 15000 });

    // Verify we are on the post edit page
    await expect(page).toHaveURL(/\/posts\/.*\/edit/);
  });

  // --- 3. Verify the team drafts page lists the draft ---
  // The arena redesign moved drafts off the team home onto the dedicated
  // `/team-drafts` page, so navigate there instead of the home URL.

  test("Team drafts page shows the draft for creators", async ({ page }) => {
    await goto(page, `/${teamUsername}/team-drafts`);

    // The drafts page renders the team-arena layout plus the drafts grid.
    await expect(
      page.getByRole("heading", { name: "Drafts", exact: true }),
    ).toBeVisible({ timeout: 15000 });
  });

  // --- 4. Verify draft card content ---

  test("Draft card displays title and Draft badge", async ({ page }) => {
    await goto(page, `/${teamUsername}/team-drafts`);

    // The draft card should display the post title.
    await expect(page.getByText(postTitle)).toBeVisible({ timeout: 15000 });

    // The draft card should display a "Draft" status badge.
    await expect(page.getByText("Draft", { exact: true }).first()).toBeVisible();
  });

  // --- 5. Click a draft card and verify navigation to the edit page ---

  test("Clicking a draft card navigates to the post edit page", async ({
    page,
  }) => {
    await goto(page, `/${teamUsername}/team-drafts`);

    // Wait for the draft list to render.
    await expect(page.getByText(postTitle)).toBeVisible({ timeout: 15000 });

    // Click the draft card containing the post title.
    await page.getByText(postTitle).click();
    await page.waitForLoadState("load");

    // Verify navigation to the post edit page.
    await expect(page).toHaveURL(/\/posts\/.*\/edit/);

    // Verify the post title is in the editor.
    const titleInput = page.getByPlaceholder("Title your post…");
    await expect(titleInput).toBeVisible();
    await expect(titleInput).toHaveValue(postTitle);
  });
});
