import { test, expect } from "@playwright/test";
import { goto, click, getLocator, waitPopup } from "../utils";

/**
 * MobileBottomNav Component — E2E Tests
 *
 * Tests the mobile bottom navigation bar introduced in issue #1272.
 *
 * Behavior under test:
 *   - Not logged in: Bottom nav shows Home and More. Tapping More opens a
 *     panel with Theme toggle, Language toggle, and Sign In button.
 *   - Logged in: Bottom nav shows Home, a highlighted "+" Create Post button,
 *     and More. Tapping More opens the sidebar sheet.
 *   - Desktop (>= tablet breakpoint): Bottom nav is hidden (tablet:hidden).
 *
 * Test IDs used:
 *   - mobile-bottom-nav       — The bottom navigation bar container
 *   - mobile-create-post-btn  — The "+" create post button (logged in only)
 *   - mobile-more-btn         — The "More" button
 *   - mobile-more-panel       — The more menu panel (unauthenticated)
 *   - mobile-more-backdrop    — The backdrop overlay behind the more menu
 *   - mobile-sign-in-btn      — The sign-in button in the more menu
 *
 * Mobile viewport: 375x667 (iPhone SE). The bottom nav is hidden at >= tablet breakpoint (900px).
 *
 * NOTE: Authenticated tests rely on `user.json` generated by auth-setup.
 *       If running outside the full Playwright project config, ensure
 *       `user.json` exists or run auth-setup first.
 */

const MOBILE_VIEWPORT = { width: 375, height: 667 };
const DESKTOP_VIEWPORT = { width: 1440, height: 950 };

// ---------------------------------------------------------------------------
// Scenario 1: Unauthenticated user on mobile
// ---------------------------------------------------------------------------

test.describe(
  "Scenario: MobileBottomNav — unauthenticated mobile user",
  () => {
    test("should display the bottom nav bar on the home page", async ({ browser }) => {
      const context = await browser.newContext({
        viewport: MOBILE_VIEWPORT,
        storageState: { cookies: [], origins: [] },
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // The bottom nav container should be visible on mobile
        const bottomNav = await getLocator(page, { testId: "mobile-bottom-nav" });
        await expect(bottomNav).toBeVisible();

        // Home link should be present inside the nav
        await getLocator(page, { testId: "mobile-home-link" });

        // More button should be present
        await getLocator(page, { testId: "mobile-more-btn" });
      } finally {
        await context.close();
      }
    });

    test("should NOT show the create post button when logged out", async ({ browser }) => {
      const context = await browser.newContext({
        viewport: MOBILE_VIEWPORT,
        storageState: { cookies: [], origins: [] },
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // The "+" create post button is only rendered for authenticated users
        const createPostBtn = page.getByTestId("mobile-create-post-btn");
        await expect(createPostBtn).toBeHidden();
      } finally {
        await context.close();
      }
    });

    test("should open the more menu panel when tapping More", async ({ browser }) => {
      const context = await browser.newContext({
        viewport: MOBILE_VIEWPORT,
        storageState: { cookies: [], origins: [] },
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Tap the More button
        await click(page, { testId: "mobile-more-btn" });

        // The more menu panel should appear
        const morePanel = await getLocator(page, { testId: "mobile-more-panel" });
        await expect(morePanel).toBeVisible();

        // Panel should contain Theme, Language, and Sign In items
        await expect(morePanel.getByText(/Theme/)).toBeVisible();
        await expect(morePanel.getByText(/Language/)).toBeVisible();

        await getLocator(page, { testId: "mobile-sign-in-btn" });
      } finally {
        await context.close();
      }
    });

    test("should close the more menu panel when tapping the backdrop", async ({ browser }) => {
      const context = await browser.newContext({
        viewport: MOBILE_VIEWPORT,
        storageState: { cookies: [], origins: [] },
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Open the more menu first
        await click(page, { testId: "mobile-more-btn" });
        const morePanel = await getLocator(page, { testId: "mobile-more-panel" });
        await expect(morePanel).toBeVisible();

        // Click the backdrop to close the panel
        await click(page, { testId: "mobile-more-backdrop" });

        // The more menu panel should be hidden
        await expect(morePanel).toBeHidden();
      } finally {
        await context.close();
      }
    });

    test("should open login modal when tapping Sign In in the more menu", async ({ browser }) => {
      const context = await browser.newContext({
        viewport: MOBILE_VIEWPORT,
        storageState: { cookies: [], origins: [] },
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Open the more menu
        await click(page, { testId: "mobile-more-btn" });
        const morePanel = await getLocator(page, { testId: "mobile-more-panel" });
        await expect(morePanel).toBeVisible();

        // Tap Sign In
        await click(page, { testId: "mobile-sign-in-btn" });

        // The more menu should close after tapping Sign In
        await expect(morePanel).toBeHidden();

        // The login popup/modal should appear
        await waitPopup(page, { visible: true });
      } finally {
        await context.close();
      }
    });
  }
);

// ---------------------------------------------------------------------------
// Scenario 2: Authenticated user on mobile
// ---------------------------------------------------------------------------

test.describe(
  "Scenario: MobileBottomNav — authenticated mobile user",
  () => {
    test("should display the bottom nav bar with create post button", async ({ browser }) => {
      const context = await browser.newContext({
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // The bottom nav container should be visible on mobile
        const bottomNav = await getLocator(page, { testId: "mobile-bottom-nav" });
        await expect(bottomNav).toBeVisible();

        // Home link
        await getLocator(page, { testId: "mobile-home-link" });

        // More button
        await getLocator(page, { testId: "mobile-more-btn" });

        // The "+" create post button should be visible for logged-in users
        await getLocator(page, { testId: "mobile-create-post-btn" });
      } finally {
        await context.close();
      }
    });

    test("should NOT show the unauthenticated more menu panel when tapping More", async ({ browser }) => {
      const context = await browser.newContext({
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // For logged-in users, tapping More opens the sidebar sheet, not the
        // unauthenticated more menu panel.
        await click(page, { testId: "mobile-more-btn" });

        // The unauthenticated more panel should NOT appear
        const morePanel = page.getByTestId("mobile-more-panel");
        await expect(morePanel).toBeHidden();
      } finally {
        await context.close();
      }
    });

    test("should navigate to post editor when tapping create post button", async ({ browser }) => {
      const context = await browser.newContext({
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Tap the create post button using the shared click helper
        await click(page, { testId: "mobile-create-post-btn" });

        // Should navigate to the post edit page
        await expect(page).toHaveURL(/\/posts\/.*\/edit/);
      } finally {
        await context.close();
      }
    });
  }
);

// ---------------------------------------------------------------------------
// Scenario 3: Desktop viewport — bottom nav should be hidden
// ---------------------------------------------------------------------------

test.describe(
  "Scenario: MobileBottomNav — hidden on desktop viewport",
  () => {
    test("should NOT display the bottom nav bar on desktop", async ({ browser }) => {
      const context = await browser.newContext({
        viewport: DESKTOP_VIEWPORT,
        storageState: { cookies: [], origins: [] },
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // The bottom nav should be hidden at desktop width (>= tablet breakpoint)
        const bottomNav = page.getByTestId("mobile-bottom-nav");
        await expect(bottomNav).toBeHidden();
      } finally {
        await context.close();
      }
    });
  }
);
