import { test, expect } from "@playwright/test";
import { goto, clickNoNav } from "../utils";
import { CONFIGS } from "../config";

/**
 * Mobile Sidebar UI — E2E Tests (issue #1309)
 *
 * Tests that the mobile sidebar sheet shows labels next to navigation icons
 * and displays the team list inline below the navigation items with a separator,
 * instead of in a popup positioned to the right that gets cut off.
 *
 * Behavior under test:
 *   - On mobile, sidebar shows expanded mode with labels next to icons
 *   - On mobile, team list appears inline in sidebar content with a "Teams" header
 *   - On mobile, the profile dropdown does not contain team items (they are inline)
 *   - On mobile, the expand/collapse toggle is hidden
 *
 * Test IDs used:
 *   - mobile-bottom-nav          — The bottom navigation bar container
 *   - mobile-more-btn            — The "More" button to open sidebar
 *   - mobile-create-post-btn     — Create post button (confirms auth state)
 *   - mobile-sidebar-content     — The inner content wrapper inside the Sheet dialog
 *   - mobile-sidebar-user-link   — User profile link in inline team section
 *   - mobile-sidebar-team-link   — Team link(s) in inline team section
 *   - sidebar-profile-btn        — Profile button in sidebar footer
 *
 * Mobile viewport: 375x667 (iPhone SE).
 *
 * NOTE: Authenticated tests rely on `user.json` generated by auth-setup.
 *       Backend must be built with `--features bypass` for hardcoded codes.
 */

const MOBILE_VIEWPORT = { width: 375, height: 667 };

/**
 * Opens the mobile sidebar sheet by clicking the More button and waits
 * for the inner content to be visible.
 *
 * Uses the shared `clickNoNav` helper (no navigation occurs) and waits
 * for the `mobile-sidebar-content` test ID to become visible instead of
 * relying on fixed `waitForTimeout` delays.  Retries the click once if
 * the content does not appear, to handle the case where the first click
 * fires before Dioxus has fully attached event handlers during hydration.
 *
 * @returns {import("@playwright/test").Locator} The sidebar content locator.
 */
async function openMobileSidebar(page) {
  await clickNoNav(page, { testId: "mobile-more-btn" });

  const sidebarContent = page.getByTestId("mobile-sidebar-content");

  try {
    await expect(sidebarContent).toBeVisible({ timeout: 10000 });
  } catch {
    // Retry: first click may have fired before Dioxus attached event handlers
    await clickNoNav(page, { testId: "mobile-more-btn" });
    await expect(sidebarContent).toBeVisible({ timeout: 10000 });
  }

  return sidebarContent;
}

// ---------------------------------------------------------------------------
// Scenario 1: Authenticated mobile user — sidebar labels
// ---------------------------------------------------------------------------

test.describe(
  "Scenario: Mobile sidebar — labels visible next to icons",
  () => {
    test("should show navigation labels in mobile sidebar sheet", async ({ browser }) => {
      const context = await browser.newContext({
        baseURL: CONFIGS.BASE_URL,
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Wait for auth hydration — create-post button confirms logged-in state
        await expect(page.getByTestId("mobile-create-post-btn")).toBeVisible();

        // Open the mobile sidebar sheet via More button
        const sidebarContent = await openMobileSidebar(page);

        // Navigation labels should be visible (not icon-only collapsed mode)
        await expect(sidebarContent.getByText("Home", { exact: true })).toBeVisible();
        await expect(sidebarContent.getByText("Membership", { exact: true })).toBeVisible();
      } finally {
        await context.close();
      }
    });

    test("should NOT show the expand/collapse toggle on mobile sidebar", async ({ browser }) => {
      const context = await browser.newContext({
        baseURL: CONFIGS.BASE_URL,
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Wait for auth hydration
        await expect(page.getByTestId("mobile-create-post-btn")).toBeVisible();

        // Open mobile sidebar
        const sidebarContent = await openMobileSidebar(page);

        // Wait for sidebar content to render before checking absence
        await expect(sidebarContent.getByText("Home", { exact: true })).toBeVisible();

        // The Collapse/Expand button should not be present on mobile
        const collapseBtn = sidebarContent.getByText("Collapse", { exact: true });
        await expect(collapseBtn).toBeHidden();
      } finally {
        await context.close();
      }
    });
  }
);

// ---------------------------------------------------------------------------
// Scenario 2: Authenticated mobile user — inline team list
// ---------------------------------------------------------------------------

test.describe(
  "Scenario: Mobile sidebar — inline team list with separator",
  () => {
    test("should show user profile link in inline team section", async ({ browser }) => {
      const context = await browser.newContext({
        baseURL: CONFIGS.BASE_URL,
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Wait for auth hydration
        await expect(page.getByTestId("mobile-create-post-btn")).toBeVisible();

        // Open mobile sidebar
        const sidebarContent = await openMobileSidebar(page);

        // The "Teams" section header should be visible
        await expect(sidebarContent.getByText("Teams", { exact: true })).toBeVisible();

        // The user profile link should be visible in the inline team section
        const userLink = sidebarContent.getByTestId("mobile-sidebar-user-link");
        await expect(userLink).toBeVisible();
      } finally {
        await context.close();
      }
    });

    test("should show profile dropdown without team items on mobile", async ({ browser }) => {
      const context = await browser.newContext({
        baseURL: CONFIGS.BASE_URL,
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Wait for auth hydration
        await expect(page.getByTestId("mobile-create-post-btn")).toBeVisible();

        // Open mobile sidebar
        const sidebarContent = await openMobileSidebar(page);

        // Click profile button to open dropdown
        const profileBtn = sidebarContent.getByTestId("sidebar-profile-btn");
        await expect(profileBtn).toBeVisible();
        await profileBtn.click();

        // The dropdown should contain logout button — it renders outside the
        // sidebar-mobile-inner div (in the ProfileButton's relative wrapper),
        // so search the full page rather than scoping to sidebarContent.
        const logoutBtn = page.getByTestId("sidebar-logout-btn");
        await expect(logoutBtn).toBeVisible();

        // The dropdown should contain "Create Team" option
        await expect(page.getByText("Create Team", { exact: true })).toBeVisible();

        // The dropdown should NOT contain any team items — on mobile, team
        // links are rendered inline in the sidebar content with testid
        // "mobile-sidebar-team-link". Scope check to the dropdown container
        // (parent of the logout button) so we don't count the inline ones.
        const profileDropdown = logoutBtn.locator("..");
        await expect(
          profileDropdown.getByTestId("mobile-sidebar-team-link")
        ).toHaveCount(0);
      } finally {
        await context.close();
      }
    });
  }
);
