import { test, expect } from "@playwright/test";
import { goto, click, getLocator } from "../utils";

/**
 * MobileBottomNav Component — E2E Tests
 *
 * Tests the mobile bottom navigation bar introduced in issue #1272.
 *
 * Behavior under test:
 *   - Not logged in: Bottom nav shows Home and More. Tapping More opens a
 *     panel with Theme toggle, Language toggle, and Sign In button.
 *   - Logged in: Bottom nav shows Home, a highlighted "+" Create Post button,
 *     and More. Tapping More opens the sidebar sheet.
 *   - Desktop (>= 768px): Bottom nav is hidden (md:hidden).
 *
 * Test IDs used:
 *   - mobile-bottom-nav       — The bottom navigation bar container
 *   - mobile-create-post-btn  — The "+" create post button (logged in only)
 *   - mobile-more-btn         — The "More" button
 *   - mobile-more-panel       — The more menu panel (unauthenticated)
 *   - mobile-sign-in-btn      — The sign-in button in the more menu
 *
 * Mobile viewport: 375x667 (iPhone SE). The bottom nav is hidden at >= 768px.
 *
 * NOTE: Authenticated tests rely on `user.json` generated by auth-setup.
 *       If running outside the full Playwright project config, ensure
 *       `user.json` exists or run auth-setup first.
 */

const MOBILE_VIEWPORT = { width: 375, height: 667 };
const DESKTOP_VIEWPORT = { width: 1440, height: 950 };

// ---------------------------------------------------------------------------
// Scenario 1: Unauthenticated user on mobile
// ---------------------------------------------------------------------------

test.describe.serial(
  "Scenario: MobileBottomNav — unauthenticated mobile user",
  () => {
    let context;
    let page;

    test.beforeAll(async ({ browser }) => {
      // Fresh context with no auth state and a mobile viewport
      context = await browser.newContext({
        viewport: MOBILE_VIEWPORT,
        storageState: { cookies: [], origins: [] },
      });
      page = await context.newPage();
    });

    test.afterAll(async () => {
      await context.close();
    });

    test("should display the bottom nav bar on the home page", async () => {
      await goto(page, "/");
      await expect(page).toHaveURL("/");

      // The bottom nav container should be visible on mobile
      const bottomNav = page.getByTestId("mobile-bottom-nav");
      await expect(bottomNav).toBeVisible();

      // Home link should be present inside the nav
      await expect(bottomNav.getByText("Home", { exact: true })).toBeVisible();

      // More button should be present
      const moreBtn = page.getByTestId("mobile-more-btn");
      await expect(moreBtn).toBeVisible();
    });

    test("should NOT show the create post button when logged out", async () => {
      // The "+" create post button is only rendered for authenticated users
      const createPostBtn = page.getByTestId("mobile-create-post-btn");
      await expect(createPostBtn).toBeHidden();
    });

    test("should open the more menu panel when tapping More", async () => {
      // Tap the More button
      await click(page, { testId: "mobile-more-btn" });

      // The more menu panel should appear
      const morePanel = page.getByTestId("mobile-more-panel");
      await expect(morePanel).toBeVisible();

      // Panel should contain Theme, Language, and Sign In items
      await expect(morePanel.getByText(/Theme/)).toBeVisible();
      await expect(morePanel.getByText(/Language/)).toBeVisible();

      const signInBtn = page.getByTestId("mobile-sign-in-btn");
      await expect(signInBtn).toBeVisible();
    });

    test("should close the more menu panel when tapping the backdrop", async () => {
      // The backdrop covers the area outside the panel (fixed inset-0).
      // Click the top portion of the page (above the panel) to hit the backdrop.
      await page.mouse.click(MOBILE_VIEWPORT.width / 2, 50);

      // The more menu panel should be hidden
      const morePanel = page.getByTestId("mobile-more-panel");
      await expect(morePanel).toBeHidden();
    });

    test("should open login modal when tapping Sign In in the more menu", async () => {
      // Re-open the more menu
      await click(page, { testId: "mobile-more-btn" });
      const morePanel = page.getByTestId("mobile-more-panel");
      await expect(morePanel).toBeVisible();

      // Tap Sign In
      await click(page, { testId: "mobile-sign-in-btn" });

      // The more menu should close after tapping Sign In
      await expect(morePanel).toBeHidden();

      // The login popup/modal should appear (identified by backdrop blur overlay)
      await expect(
        page.locator(".backdrop-blur-\\[10px\\]")
      ).toBeVisible();
    });
  }
);

// ---------------------------------------------------------------------------
// Scenario 2: Authenticated user on mobile
// ---------------------------------------------------------------------------

test.describe.serial(
  "Scenario: MobileBottomNav — authenticated mobile user",
  () => {
    let context;
    let page;

    test.beforeAll(async ({ browser }) => {
      // Use saved auth state with mobile viewport.
      // user.json is generated by the auth-setup project.
      context = await browser.newContext({
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      page = await context.newPage();
    });

    test.afterAll(async () => {
      await context.close();
    });

    test("should display the bottom nav bar with create post button", async () => {
      await goto(page, "/");
      await expect(page).toHaveURL("/");

      // The bottom nav container should be visible on mobile
      const bottomNav = page.getByTestId("mobile-bottom-nav");
      await expect(bottomNav).toBeVisible();

      // Home link
      await expect(bottomNav.getByText("Home", { exact: true })).toBeVisible();

      // More button
      const moreBtn = page.getByTestId("mobile-more-btn");
      await expect(moreBtn).toBeVisible();

      // The "+" create post button should be visible for logged-in users
      const createPostBtn = page.getByTestId("mobile-create-post-btn");
      await expect(createPostBtn).toBeVisible();
    });

    test("should NOT show the unauthenticated more menu panel when tapping More", async () => {
      // For logged-in users, tapping More opens the sidebar sheet, not the
      // unauthenticated more menu panel.
      await click(page, { testId: "mobile-more-btn" });

      // The unauthenticated more panel should NOT appear
      const morePanel = page.getByTestId("mobile-more-panel");
      await expect(morePanel).toBeHidden();
    });

    test("should navigate to post editor when tapping create post button", async () => {
      // Reload to reset any open sidebar state
      await goto(page, "/");

      // Tap the create post button
      const createPostBtn = page.getByTestId("mobile-create-post-btn");
      await expect(createPostBtn).toBeVisible();
      await createPostBtn.click();

      // Should navigate to the post edit page
      await page.waitForURL(/\/posts\/.*\/edit/, { waitUntil: "load" });
      await expect(page).toHaveURL(/\/posts\/.*\/edit/);
    });
  }
);

// ---------------------------------------------------------------------------
// Scenario 3: Desktop viewport — bottom nav should be hidden
// ---------------------------------------------------------------------------

test.describe.serial(
  "Scenario: MobileBottomNav — hidden on desktop viewport",
  () => {
    let context;
    let page;

    test.beforeAll(async ({ browser }) => {
      // Desktop viewport — bottom nav uses md:hidden (>= 768px)
      context = await browser.newContext({
        viewport: DESKTOP_VIEWPORT,
        storageState: { cookies: [], origins: [] },
      });
      page = await context.newPage();
    });

    test.afterAll(async () => {
      await context.close();
    });

    test("should NOT display the bottom nav bar on desktop", async () => {
      await goto(page, "/");
      await expect(page).toHaveURL("/");

      // The bottom nav should be hidden at desktop width (>= 768px / md breakpoint)
      const bottomNav = page.getByTestId("mobile-bottom-nav");
      await expect(bottomNav).toBeHidden();
    });
  }
);
