import { test, expect } from "@playwright/test";
import { goto } from "../utils";
import { CONFIGS } from "../config";

/**
 * Mobile Sidebar UI — E2E Tests (issue #1309)
 *
 * Tests that the mobile sidebar sheet shows labels next to navigation icons
 * and displays the team list inline below the navigation items with a separator,
 * instead of in a popup positioned to the right that gets cut off.
 *
 * Behavior under test:
 *   - On mobile, sidebar shows expanded mode with labels next to icons
 *   - On mobile, team list appears inline in sidebar content with a "Teams" header
 *   - On mobile, the profile dropdown does not contain team items (they are inline)
 *   - On mobile, the expand/collapse toggle is hidden
 *
 * Test IDs used:
 *   - mobile-bottom-nav          — The bottom navigation bar container
 *   - mobile-more-btn            — The "More" button to open sidebar
 *   - mobile-create-post-btn     — Create post button (confirms auth state)
 *   - mobile-sidebar-sheet       — The sidebar content wrapper inside the Sheet dialog
 *   - mobile-sidebar-user-link   — User profile link in inline team section
 *   - mobile-sidebar-team-link   — Team link(s) in inline team section
 *   - sidebar-profile-btn        — Profile button in sidebar footer
 *
 * Mobile viewport: 375x667 (iPhone SE).
 *
 * NOTE: Authenticated tests rely on `user.json` generated by auth-setup.
 *       Backend must be built with `--features bypass` for hardcoded codes.
 */

const MOBILE_VIEWPORT = { width: 375, height: 667 };

/**
 * Opens the mobile sidebar sheet by clicking the More button.
 * Uses force:true to bypass DOM-stability checks (post-hydration effects
 * like is_mobile detection can keep mutating the DOM). Retries the click
 * once if the sidebar sheet does not appear within a short window, to
 * handle the case where the first click fires before Dioxus has fully
 * attached event handlers during hydration.
 *
 * @returns {import("@playwright/test").Locator} The sidebar sheet locator.
 */
async function openMobileSidebar(page) {
  const moreBtn = page.getByTestId("mobile-more-btn");
  await expect(moreBtn).toBeVisible();
  await moreBtn.click({ force: true });

  const sidebarSheet = page.getByTestId("mobile-sidebar-sheet");

  // Give Dioxus a short window to process the click and render the Sheet.
  // If the sheet doesn't appear, retry the click once — the first click may
  // have fired before hydration finished attaching event handlers.
  try {
    await expect(sidebarSheet).toBeVisible({ timeout: 3000 });
  } catch {
    await moreBtn.click({ force: true });
    await expect(sidebarSheet).toBeVisible();
  }

  return sidebarSheet;
}

// ---------------------------------------------------------------------------
// Scenario 1: Authenticated mobile user — sidebar labels
// ---------------------------------------------------------------------------

test.describe(
  "Scenario: Mobile sidebar — labels visible next to icons",
  () => {
    test("should show navigation labels in mobile sidebar sheet", async ({ browser }) => {
      const context = await browser.newContext({
        baseURL: CONFIGS.BASE_URL,
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Wait for auth hydration — create-post button confirms logged-in state
        await expect(page.getByTestId("mobile-create-post-btn")).toBeVisible();

        // Open the mobile sidebar sheet via More button
        const sidebarSheet = await openMobileSidebar(page);

        // Navigation labels should be visible (not icon-only collapsed mode)
        await expect(sidebarSheet.getByText("Home", { exact: true })).toBeVisible();
        await expect(sidebarSheet.getByText("Membership", { exact: true })).toBeVisible();
      } finally {
        await context.close();
      }
    });

    test("should NOT show the expand/collapse toggle on mobile sidebar", async ({ browser }) => {
      const context = await browser.newContext({
        baseURL: CONFIGS.BASE_URL,
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Wait for auth hydration
        await expect(page.getByTestId("mobile-create-post-btn")).toBeVisible();

        // Open mobile sidebar
        const sidebarSheet = await openMobileSidebar(page);

        // The Collapse/Expand button should not be present on mobile
        const collapseBtn = sidebarSheet.getByText("Collapse", { exact: true });
        await expect(collapseBtn).toBeHidden();
      } finally {
        await context.close();
      }
    });
  }
);

// ---------------------------------------------------------------------------
// Scenario 2: Authenticated mobile user — inline team list
// ---------------------------------------------------------------------------

test.describe(
  "Scenario: Mobile sidebar — inline team list with separator",
  () => {
    test("should show user profile link in inline team section", async ({ browser }) => {
      const context = await browser.newContext({
        baseURL: CONFIGS.BASE_URL,
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Wait for auth hydration
        await expect(page.getByTestId("mobile-create-post-btn")).toBeVisible();

        // Open mobile sidebar
        const sidebarSheet = await openMobileSidebar(page);

        // The "Teams" section header should be visible
        await expect(sidebarSheet.getByText("Teams", { exact: true })).toBeVisible();

        // The user profile link should be visible in the inline team section
        const userLink = sidebarSheet.getByTestId("mobile-sidebar-user-link");
        await expect(userLink).toBeVisible();
      } finally {
        await context.close();
      }
    });

    test("should show profile dropdown without team items on mobile", async ({ browser }) => {
      const context = await browser.newContext({
        baseURL: CONFIGS.BASE_URL,
        viewport: MOBILE_VIEWPORT,
        storageState: "user.json",
      });
      const page = await context.newPage();

      try {
        await goto(page, "/");

        // Wait for auth hydration
        await expect(page.getByTestId("mobile-create-post-btn")).toBeVisible();

        // Open mobile sidebar
        const sidebarSheet = await openMobileSidebar(page);

        // Click profile button to open dropdown
        const profileBtn = sidebarSheet.getByTestId("sidebar-profile-btn");
        await expect(profileBtn).toBeVisible();
        await profileBtn.click();

        // The dropdown should contain logout button
        const logoutBtn = sidebarSheet.getByTestId("sidebar-logout-btn");
        await expect(logoutBtn).toBeVisible();

        // The dropdown should contain "Create Team" option
        await expect(sidebarSheet.getByText("Create Team", { exact: true })).toBeVisible();
      } finally {
        await context.close();
      }
    });
  }
);
