#!/bin/bash

echo "Generating .env.local from environment variables..."


cat > .env.local <<EOL
NEXT_PUBLIC_ENV=${ENV}
NEXT_PUBLIC_LOG_LEVEL=${LOG_LEVEL}
NEXT_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
NEXT_PUBLIC_FIREBASE_APP_ID=${FIREBASE_APP_ID}
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}

# for local docker
# NEXT_PUBLIC_ENABLE_SERVER_CONFIG=true
# NEXT_PUBLIC_API_URL=http://localhost:3000
# NEXT_PUBLIC_EXPERIMENT=false
# NEXT_PUBLIC_GRAPHQL_URL=http://localhost:28080/v1/graphql


# for dev
NEXT_PUBLIC_ENABLE_SERVER_CONFIG=false
NEXT_PUBLIC_API_URL=https://api.dev.ratel.foundation
NEXT_PUBLIC_EXPERIMENT=false
NEXT_PUBLIC_GRAPHQL_URL=https://graphql.dev.ratel.foundation/v1/graphql
EOL

echo ".env.local created successfully."
