#!/bin/bash

echo "Generating .env.local from environment variables..."


cat > .env.local <<EOL
NEXT_PUBLIC_ENV=${ENV}
NEXT_PUBLIC_LOG_LEVEL=${LOG_LEVEL}
NEXT_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
NEXT_PUBLIC_FIREBASE_APP_ID=${FIREBASE_APP_ID}
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}

NEXT_PUBLIC_SIGN_DOMAIN=${SIGN_DOMAIN}
NEXT_PUBLIC_API_URL=${MAIN_API_ENDPOINT}
NEXT_PUBLIC_EXPERIMENT=true
NEXT_PUBLIC_GRAPHQL_URL=${GRAPHQL_API_ENDPOINT}
EOL

echo ".env.local created successfully."
