// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOkL9ndDuaY3bLl2t8EFppnu0K_eFmdZ0',
    appId: '1:925748630857:android:21bade2376f06f480d3698',
    messagingSenderId: '925748630857',
    projectId: 'ratel-eef15',
    storageBucket: 'ratel-eef15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtB5d1LE0E-nx9IQFi-H_EWXYeX76uA8U',
    appId: '1:925748630857:ios:6398b2828de79f0c0d3698',
    messagingSenderId: '925748630857',
    projectId: 'ratel-eef15',
    storageBucket: 'ratel-eef15.firebasestorage.app',
    androidClientId: '925748630857-mmgq18au9c5sclfu2vo6ll9nd946cl74.apps.googleusercontent.com',
    iosClientId: '925748630857-gla98vdbf4th33ahd0shlsu47qnp0u90.apps.googleusercontent.com',
    iosBundleId: 'foundation.ratel.app',
  );
}
