mod alert;
mod arrows;
mod background_triangle;
mod chat;
mod circle_down;
mod clock;
mod close;
pub mod coming_soon;
mod cons;
mod double_arrow;
mod file_upload;
mod hand_palm;
mod logos;
mod money;
mod mouse_scroll;
mod palace;
mod party_logos;
mod pentagon2;
mod pptx_file;
mod pros;
mod ratel_circle;
mod reward_coin;
mod search;
mod slide_ball;
mod sort;
mod thumbs;
mod tooltip;
mod votes;
mod wallet;

pub use alert::*;
pub use arrows::*;
pub use background_triangle::*;
pub use chat::*;
pub use circle_down::*;
pub use clock::*;
pub use close::*;
pub use coming_soon::*;
pub use cons::*;
pub use double_arrow::*;
pub use file_upload::*;
pub use hand_palm::*;
pub use logos::*;
pub use money::*;
pub use mouse_scroll::*;
pub use palace::*;
pub use party_logos::*;
pub use pentagon2::*;
pub use pptx_file::*;
pub use pros::*;
pub use ratel_circle::*;
pub use reward_coin::*;
pub use search::*;
pub use slide_ball::*;
pub use sort::*;
pub use thumbs::*;
pub use tooltip::*;
pub use votes::*;
pub use wallet::*;
