name: Production deploy

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [ratel-app, ratel-app-lambda]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}
      # - name: Write Firebase service account (prod)
      #   run: |
      #     mkdir -p cdk/main-api/.gcp
      #     echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON_BASE64 }}" \
      #       | base64 -d > cdk/main-api/.gcp/firebase-service-account.json

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Deploy
        env:
          ENV: prod
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOMAIN: ratel.foundation
          STACK: ratel-prod-stack
          DEPLOY_STORYBOOK: false
          DEPLOY_STATIC: false
          HIGH_TRAFFIC_REGION: ap-northeast-2
        run: |
          npm i -g aws-cdk
          make cdk-deploy-v2

  ratel-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: ratel-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Restore cache
        id: app-shell-build-cache
        uses: actions/cache/restore@v4
        with:
          key: app-shell-build-${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            app-shell-build-${{ runner.os }}-rust-
          path: |
            ~/.cargo/bin
            target

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable
          target: wasm32-unknown-unknown
          cache: false

      - uses: cargo-bins/cargo-binstall@main
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            lld

      - name: Install Dioxus-cli
        run: |
          cargo binstall dioxus-cli --force

      - name: Building APIs
        env:
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          ENV: prod
          RUST_LOG: error
          SERVICE: app-shell
          DOMAIN: ratel.foundation
          BUCKET_NAME: metadata.ratel.foundation
          SLACK_HOOK: ${{ secrets.SLACK_HOOK }}

          BINANCE_API_KEY: ${{ secrets.PROD_BINANCE_API_KEY }}
          BINANCE_SECRET_KEY: ${{ secrets.PROD_BINANCE_SECRET_KEY }}
          BINANCE_WEBHOOK: https://api.ratel.foundation/v2/binances/webhooks
          REDIRECT_DOMAIN: https://ratel.foundation

          KAIA_ENDPOINT: https://public-en.node.kaia.io
          KAIA_ARCHIVE_ENDPOINT: https://archive-en.node.kaia.io
          KAIA_FEEPAYER_KEY: ${{ secrets.PROD_KAIA_FEEPAYER_KEY }}
          KAIA_FEEPAYER_ADDR: ${{ secrets.PROD_KAIA_FEEPAYER_ADDR }}
          KAIA_OWNER_KEY: ${{ secrets.PROD_KAIA_OWNER_KEY }}
          KAIA_OWNER_ADDR: ${{ secrets.PROD_KAIA_OWNER_KEY_ADDR }}

          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

          BBS_BLS_X: ${{ secrets.BBS_BLS_X }}
          BBS_BLS_Y: ${{ secrets.BBS_BLS_Y }}
          BBS_BLS_D: ${{ secrets.BBS_BLS_D }}
          BBS_BLS_CRV: ${{ secrets.BBS_BLS_CRV }}

          P256_X: ${{ secrets.P256_X }}
          P256_Y: ${{ secrets.P256_Y }}
          P256_D: ${{ secrets.P256_D }}
          P256_CRV: ${{ secrets.P256_CRV }}

          DYNAMO_TABLE_PREFIX: ratel-prod
          DYNAMO_ENDPOINT: none
          # RUST_FLAG: "--features lambda --release"
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

          FCM_ENABLED: true
          RATEL_PROJECT_ID: ${{ secrets.RATEL_PROJECT_ID }}
          REWARD: true

          BEDROCK_AGENT_ID: ${{ secrets.PROD_BEDROCK_AGENT_ID }}
          BEDROCK_AGENT_ALIAS_ID: ${{ secrets.PROD_BEDROCK_AGENT_ALIAS_ID }}

          BIYARD_API_KEY: ${{ secrets.BIYARD_API_KEY }}
          BIYARD_PROJECT_ID: ${{ secrets.BIYARD_PROJECT_ID }}

          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

          # NOTE: Change PORTONE API
          PORTONE_API_SECRET: ${{ secrets.PORTONE_API_SECRET }}
          PORTONE_KPN_CHANNEL_KEY: ${{ secrets.PORTONE_KPN_BILLING_KEY_CHANNEL_KEY }}
          PORTONE_STORE_ID: ${{ secrets.PORTONE_STORE_ID }}
          PORTONE_INICIS_CHANNEL_KEY: ${{ secrets.PROD_PORTONE_INICIS_CHANNEL_KEY }}

          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{secrets.QDRANT_API_KEY }}

          ECR: ${{ steps.ratel-ecr.outputs.registry }}/ratel/app-shell

          WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID }}
        run: |
          npm i
          rm -rf target/dx

          cd app/ratel
          make build
          make docker
          make docker.push

      - name: Deploy to S3
        env:
          BUCKET: ${{ secrets.PROD_RATEL_BUCKET }}
          CDN: ${{ secrets.PROD_RATEL_CDN }}
        run: |
          aws s3 sync target/dx/app-shell/release/web/public $BUCKET
          aws cloudfront create-invalidation --distribution-id $CDN --paths "/*"
          tar czvf app-shell.tar.gz target/dx/app-shell/release/web

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-shell-${{ github.sha }}
          path: ${{ github.workspace }}/app-shell.tar.gz
          if-no-files-found: error
          retention-days: 7

  ratel-app-lambda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: ratel-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Restore cache
        id: app-shell-build-cache
        uses: actions/cache/restore@v4
        with:
          key: app-shell-lambda-build-${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            app-shell-lambda-build-${{ runner.os }}-rust-
          path: |
            ~/.cargo/bin
            target

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable
          target: wasm32-unknown-unknown
          cache: false

      - uses: cargo-bins/cargo-binstall@main
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            lld

      - name: Install Dioxus-cli
        run: |
          cargo binstall dioxus-cli --force

      - name: Building APIs
        env:
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          ENV: prod
          RUST_LOG: info
          SERVICE: app-shell
          DOMAIN: ratel.foundation
          BUCKET_NAME: metadata.ratel.foundation
          SLACK_HOOK: ${{ secrets.SLACK_HOOK }}

          BINANCE_API_KEY: ${{ secrets.PROD_BINANCE_API_KEY }}
          BINANCE_SECRET_KEY: ${{ secrets.PROD_BINANCE_SECRET_KEY }}
          BINANCE_WEBHOOK: https://api.ratel.foundation/v2/binances/webhooks
          REDIRECT_DOMAIN: https://ratel.foundation

          KAIA_ENDPOINT: https://public-en.node.kaia.io
          KAIA_ARCHIVE_ENDPOINT: https://archive-en.node.kaia.io
          KAIA_FEEPAYER_KEY: ${{ secrets.PROD_KAIA_FEEPAYER_KEY }}
          KAIA_FEEPAYER_ADDR: ${{ secrets.PROD_KAIA_FEEPAYER_ADDR }}
          KAIA_OWNER_KEY: ${{ secrets.PROD_KAIA_OWNER_KEY }}
          KAIA_OWNER_ADDR: ${{ secrets.PROD_KAIA_OWNER_KEY_ADDR }}

          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

          BBS_BLS_X: ${{ secrets.BBS_BLS_X }}
          BBS_BLS_Y: ${{ secrets.BBS_BLS_Y }}
          BBS_BLS_D: ${{ secrets.BBS_BLS_D }}
          BBS_BLS_CRV: ${{ secrets.BBS_BLS_CRV }}

          P256_X: ${{ secrets.P256_X }}
          P256_Y: ${{ secrets.P256_Y }}
          P256_D: ${{ secrets.P256_D }}
          P256_CRV: ${{ secrets.P256_CRV }}

          DYNAMO_TABLE_PREFIX: ratel-prod
          DYNAMO_ENDPOINT: none
          # RUST_FLAG: "--features lambda --release"
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

          FCM_ENABLED: true
          RATEL_PROJECT_ID: ${{ secrets.RATEL_PROJECT_ID }}
          REWARD: true

          BEDROCK_AGENT_ID: ${{ secrets.PROD_BEDROCK_AGENT_ID }}
          BEDROCK_AGENT_ALIAS_ID: ${{ secrets.PROD_BEDROCK_AGENT_ALIAS_ID }}

          BIYARD_API_KEY: ${{ secrets.BIYARD_API_KEY }}
          BIYARD_PROJECT_ID: ${{ secrets.BIYARD_PROJECT_ID }}

          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

          # NOTE: Change PORTONE API
          PORTONE_API_SECRET: ${{ secrets.PORTONE_API_SECRET }}
          PORTONE_KPN_CHANNEL_KEY: ${{ secrets.PORTONE_KPN_BILLING_KEY_CHANNEL_KEY }}
          PORTONE_STORE_ID: ${{ secrets.PORTONE_STORE_ID }}
          PORTONE_INICIS_CHANNEL_KEY: ${{ secrets.PROD_PORTONE_INICIS_CHANNEL_KEY }}

          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{secrets.QDRANT_API_KEY }}

          ECR: ${{ steps.ratel-ecr.outputs.registry }}/ratel/app-shell-lambda

          WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID }}
        run: |
          npm i
          rm -rf target/dx

          cd app/ratel
          make build-lambda
          make docker
          make docker.push

      - name: Deploy to S3
        env:
          BUCKET: ${{ secrets.PROD_RATEL_BUCKET }}
          CDN: ${{ secrets.PROD_RATEL_CDN }}
        run: |
          aws s3 sync target/dx/app-shell/release/web/public $BUCKET
          aws cloudfront create-invalidation --distribution-id $CDN --paths "/*"
          tar czvf app-shell-lambda.tar.gz target/dx/app-shell/release/web

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-shell-lambda-${{ github.sha }}
          path: ${{ github.workspace }}/app-shell-lambda.tar.gz
          if-no-files-found: error
          retention-days: 7
