// Auto-generated by build.rs - DO NOT EDIT
#![allow(non_snake_case, unused_braces)]
use dioxus::prelude::*;

#[component]
pub fn Discuss(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M3 6.81161C3 5.03787 4.34248 3.59998 5.99852 3.59998H13.4948C15.1509 3.59998 16.4933 5.03787 16.4933 6.81161V13.2349C16.4933 15.0086 15.1509 16.4465 13.4948 16.4465H8.43482L7.34785 17.9988C7.048 18.427 6.4483 18.427 6.14845 17.9988L5.06148 16.4465C3.40545 16.4465 3 15.0086 3 13.2349V6.81161Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M18.8835 9.73328C19.4801 9.73328 20.0282 9.95407 20.4595 10.323C21.033 10.8136 21.4 11.566 21.4 12.4096V17.7624C21.4 19.2405 21.0597 20.4387 19.6699 20.4387L18.7577 21.7323C18.5061 22.0892 18.0028 22.0892 17.7511 21.7323L16.8389 20.4387H12.5924C11.9488 20.4387 11.3615 20.1817 10.9165 19.7589C10.6906 19.5443 10.5014 19.2869 10.36 18.9987",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M7.77522 10.9601H10.36V7.14868",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
            }
        
        }
    }
}

#[component]
pub fn Media(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M17 3H7C4.79086 3 3 4.79086 3 7V15C3 17.2091 4.54086 19 6.75 19L8.2 20.9333C8.6 21.4667 9.4 21.4667 9.8 20.9333L11.25 19H17C19.2091 19 21 17.2091 21 15V7C21 4.79086 19.2091 3 17 3Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M9 13.923V8.07699C9 7.5971 9.51843 7.29624 9.93509 7.53434L15.0504 10.4573C15.4702 10.6973 15.4702 11.3027 15.0504 11.5427L9.93509 14.4657C9.51843 14.7038 9 14.4029 9 13.923Z",
                "fill": "black",
            }
        
        }
    }
}

#[component]
pub fn RoundBubble(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "fill-rule": "evenodd",
                "clip-rule": "evenodd",
                "d": "M21 12C21.0036 13.3975 20.6771 14.7761 20.047 16.0235C18.5233 19.0722 15.4082 20.9987 12 21C10.6025 21.0036 9.2239 20.6771 7.97648 20.047L3.00003 21L3.95297 16.0235C3.3229 14.7761 2.99639 13.3975 3.00003 12C3.00135 8.59176 4.92779 5.47665 7.97648 3.95297C9.2239 3.3229 10.6025 2.99639 12 3.00003H12.5294C17.0991 3.25213 20.7479 6.90093 21 11.4706V12Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            line {
                "x-1": "8.5",
                "y-1": "8.96582",
                "x-2": "15.5",
                "y-2": "8.96582",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
            }
            path {
                "d": "M8.25 12.4707L13.25 12.4707",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
            }
            path {
                "d": "M8.25 15.7842H10.25",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
            }
        
        }
    }
}

#[component]
pub fn SquareChat(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M3 6.83337C3 4.62423 4.79086 2.83337 7 2.83337H17C19.2091 2.83337 21 4.62423 21 6.83337V14.8334C21 17.0425 19.2091 18.8334 17 18.8334H14.25L12.8 20.7667C12.4 21.3 11.6 21.3 11.2 20.7667L9.75 18.8334H7C4.79086 18.8334 3 17.0425 3 14.8334V6.83337Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            line {
                "x-1": "8.5",
                "y-1": "7.5625",
                "x-2": "15.5",
                "y-2": "7.5625",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
            }
            path {
                "d": "M8.25 11.0674L13.25 11.0674",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
            }
            path {
                "d": "M8.25 14.3809H10.25",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
            }
        
        }
    }
}

#[component]
pub fn SquareMark(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M3 6.83337C3 4.62423 4.79086 2.83337 7 2.83337H17C19.2091 2.83337 21 4.62423 21 6.83337V14.8334C21 17.0425 19.2091 18.8334 17 18.8334H14.25L12.8 20.7667C12.4 21.3 11.6 21.3 11.2 20.7667L9.75 18.8334H7C4.79086 18.8334 3 17.0425 3 14.8334V6.83337Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M15.8507 14.9688V11.5199C15.8507 10.4154 14.9553 9.51992 13.8507 9.51992H8.14931M8.14931 9.51992L10.6354 7.03381M8.14931 9.51992L10.6354 12.006",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
        
        }
    }
}

#[component]
pub fn SquareQuestion(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M10 9C10 8.60444 10.1173 8.21776 10.3371 7.88886C10.5568 7.55996 10.8692 7.30362 11.2346 7.15224C11.6001 7.00087 12.0022 6.96126 12.3902 7.03843C12.7781 7.1156 13.1345 7.30608 13.4142 7.58579C13.6939 7.86549 13.8844 8.22186 13.9616 8.60982C14.0387 8.99778 13.9991 9.39992 13.8478 9.76537C13.6964 10.1308 13.44 10.4432 13.1111 10.6629C12.7822 10.8827 12.3956 11 12 11V12M14.25 19L12.8 20.9333C12.4 21.4667 11.6 21.4667 11.2 20.9333L9.75 19H7C4.79086 19 3 17.2091 3 15V7C3 4.79086 4.79086 3 7 3H17C19.2091 3 21 4.79086 21 7V15C21 17.2091 19.2091 19 17 19H14.25Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            circle {
                "cx": "12",
                "cy": "15",
                "r": "1",
                "fill": "black",
            }
        
        }
    }
}

#[component]
pub fn SquareWarning(
    #[props(default = "24")] width: &'static str,
    #[props(default = "24")] height: &'static str,
    class: Option<&'static str>,
) -> Element {
    rsx! {
        svg {
            width,
            height,
            view_box: "0 0 24 24",
            class: class.unwrap_or_default(),
            xmlns: "http://www.w3.org/2000/svg",
            path {
                "d": "M17 3H7C4.79086 3 3 4.79086 3 7V15C3 17.2091 4.79086 19 7 19H9.75L11.2 20.9333C11.6 21.4667 12.4 21.4667 12.8 20.9333L14.25 19H17C19.2091 19 21 17.2091 21 15V7C21 4.79086 19.2091 3 17 3Z",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            path {
                "d": "M12 7.01562L12 12",
                "stroke": "black",
                "stroke-width": "2",
                "stroke-linecap": "round",
                "stroke-linejoin": "round",
            }
            circle {
                "cx": "12",
                "cy": "15",
                "r": "1",
                "fill": "black",
            }
        
        }
    }
}

