version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ratel
    ports:
      - 5432:5432

  graphql-engine:
    container_name: hasura
    image: hasura/graphql-engine:v1.0.0-beta.6
    ports:
    - "28080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: ratel
      HASURA_GRAPHQL_AUTH_HOOK: ${HASURA_GRAPHQL_AUTH_HOOK} 
      HASURA_GRAPHQL_AUTH_HOOK_MODE: POST
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup,http-log,webhook-log,query-log"
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_DEV_MODE: true
